package prenode

var generatedPrenodes = map[string]*Prenode{
	"beach":                     &Prenode{Parents: []string{"beach 1", "beach 2", "beach 3", "beach 4", "beach 5", "beach 6", "beach 7"}, Type: 2},
	"bridge":                    &Prenode{Parents: []string{"bridge 1", "bridge 2", "bridge 3"}, Type: 2},
	"d2 arrow room":             &Prenode{Parents: []string{"d2 arrow room 1", "d2 arrow room 2"}, Type: 2},
	"d2 blade key chest":        &Prenode{Parents: []string{"d2 blade key chest 1", "d2 blade key chest 2"}, Type: 2},
	"d2 compass chest":          &Prenode{Parents: []string{"d2 compass chest 1", "d2 compass chest 2"}, Type: 2},
	"d3 basement A in":          &Prenode{Parents: []string{"d3 basement A in 1", "d3 basement A in 2"}, Type: 2},
	"d3 basement A out":         &Prenode{Parents: []string{"d3 basement A out 1", "d3 basement A out 2"}, Type: 2},
	"d3 basement B in":          &Prenode{Parents: []string{"d3 basement B in 1", "d3 basement B in 2"}, Type: 2},
	"d3 basement B out":         &Prenode{Parents: []string{"d3 basement B out 1", "d3 basement B out 2"}, Type: 2},
	"d3 feather stairs":         &Prenode{Parents: []string{"d3 feather stairs 1", "d3 feather stairs 2", "d3 feather stairs 3"}, Type: 2},
	"d3 mimic stairs":           &Prenode{Parents: []string{"d3 mimic stairs 1", "d3 mimic stairs 2"}, Type: 2},
	"d3 trampoline stairs":      &Prenode{Parents: []string{"d3 trampoline stairs 1", "d3 trampoline stairs 2"}, Type: 2},
	"d5 large rupee chest":      &Prenode{Parents: []string{"d5 large rupee chest 1", "d5 large rupee chest 2"}, Type: 2},
	"d5 stairs B out":           &Prenode{Parents: []string{"d5 stairs B out 1", "d5 stairs B out 2"}, Type: 2},
	"d6 map chest":              &Prenode{Parents: []string{"d6 map chest 1", "d6 map chest 2"}, Type: 2},
	"d7 armos room":             &Prenode{Parents: []string{"d7 armos room 1", "d7 armos room 2"}, Type: 2},
	"d7 cross bridge":           &Prenode{Parents: []string{"d7 cross bridge 1", "d7 cross bridge 2", "d7 cross bridge 3"}, Type: 2},
	"d8 HSS stairs":             &Prenode{Parents: []string{"d8 HSS stairs 1", "d8 HSS stairs 2"}, Type: 2},
	"d8 cross bridge A":         &Prenode{Parents: []string{"d8 cross bridge A 1", "d8 cross bridge A 2"}, Type: 2},
	"d8 ice puzzle room":        &Prenode{Parents: []string{"d8 ice puzzle room 1", "d8 ice puzzle room 2"}, Type: 2},
	"d8 portal":                 &Prenode{Parents: []string{"d8 portal 1", "d8 portal 2"}, Type: 2},
	"dragon key cross":          &Prenode{Parents: []string{"dragon key cross 1", "dragon key cross 2"}, Type: 2},
	"enter poe sisters":         &Prenode{Parents: []string{"enter poe sisters 1", "enter poe sisters 2"}, Type: 2},
	"furnace":                   &Prenode{Parents: []string{"furnace 1", "furnace 2", "furnace 3"}, Type: 2},
	"gale tree seeds":           &Prenode{Parents: []string{"gale tree seeds 1", "gale tree seeds 2"}, Type: 2},
	"ghastly stump":             &Prenode{Parents: []string{"ghastly stump 1", "ghastly stump 2", "ghastly stump 3", "ghastly stump 4", "ghastly stump 5"}, Type: 2},
	"goron mountain":            &Prenode{Parents: []string{"goron mountain 1", "goron mountain 2", "goron mountain 3", "goron mountain 4"}, Type: 2},
	"graveyard":                 &Prenode{Parents: []string{"graveyard 1", "graveyard 2"}, Type: 2},
	"hide and seek":             &Prenode{Parents: []string{"hide and seek 1", "hide and seek 2", "hide and seek 3", "hide and seek 4"}, Type: 2},
	"horon village":             &Prenode{Parents: []string{"horon village 1", "horon village 2", "horon village 3", "horon village 4", "horon village 5", "horon village 6"}, Type: 2},
	"kill darknut (across pit)": &Prenode{Parents: []string{"kill darknut (across pit) 1", "kill darknut (across pit) 2"}, Type: 2},
	"kill frypolar":             &Prenode{Parents: []string{"kill frypolar 1", "kill frypolar 2"}, Type:2},
	"lake portal":               &Prenode{Parents: []string{"lake portal 1", "lake portal 2", "lake portal 3"}, Type: 2},
	"mount cucco":               &Prenode{Parents: []string{"mount cucco 1", "mount cucco 2", "mount cucco 3"}, Type: 2},
	"mountain portal":           &Prenode{Parents: []string{"mountain portal 1", "mountain portal 2"}, Type: 2},
	"natzu":                     &Prenode{Parents: []string{"natzu 1", "natzu 2", "natzu 3"}, Type: 2},
	"open floodgate":            &Prenode{Parents: []string{"open floodgate 1", "open floodgate 2", "open floodgate 3"}, Type: 2},
	"pirate house":              &Prenode{Parents: []string{"pirate house 1", "pirate house 2", "pirate house 3"}, Type: 2},
	"post-d2 stump":             &Prenode{Parents: []string{"post-d2 stump 1", "post-d2 stump 2", "post-d2 stump 3", "post-d2 stump 4"}, Type: 2},
	"remains portal":            &Prenode{Parents: []string{"remains portal 1", "remains portal 2", "remains portal 3", "remains portal 4"}, Type: 2},
	"ricky pen":                 &Prenode{Parents: []string{"ricky pen 1", "ricky pen 2", "ricky pen 3"}, Type: 2},
	"sokra stump":               &Prenode{Parents: []string{"sokra stump 1", "sokra stump 2", "sokra stump 3", "sokra stump 4"}, Type: 2},
	"spool swamp":               &Prenode{Parents: []string{"spool swamp 1", "spool swamp 2", "spool swamp 3"}, Type: 2},
	"sunken city":               &Prenode{Parents: []string{"sunken city 1", "sunken city 2", "sunken city 3"}, Type: 2},
	"swamp portal":              &Prenode{Parents: []string{"swamp portal 1", "swamp portal 2", "swamp portal 3", "swamp portal 4"}, Type: 2},
	"temple":                    &Prenode{Parents: []string{"temple 1", "temple 2", "temple 3", "temple 4", "temple 5"}, Type: 2},
	"temple remains":            &Prenode{Parents: []string{"temple remains 1", "temple remains 2", "temple remains 3"}, Type: 2},
	"village portal":            &Prenode{Parents: []string{"village portal 1", "village portal 2", "village portal 3"}, Type: 2},
}
