package rom

var rings = []string{
	"friendship ring",
	"power ring L-1",
	"power ring L-2",
	"power ring L-3",
	"armor ring L-1",
	"armor ring L-2",
	"armor ring L-3",
	"red ring",
	"blue ring",
	"green ring",
	"cursed ring",
	"expert's ring",
	"blast ring",
	"rang ring L-1",
	"GBA time ring",
	"maple's ring",
	"steadfast ring",
	"pegasus ring",
	"toss ring",
	"heart ring L-1",
	"heart ring L-2",
	"swimmer's ring",
	"charge ring",
	"light ring L-1",
	"light ring L-2",
	"bomber's ring",
	"green luck ring",
	"blue luck ring",
	"gold luck ring",
	"red luck ring",
	"green holy ring",
	"blue holy ring",
	"red holy ring",
	"snowshoe ring",
	"roc's ring",
	"quicksand ring",
	"red joy ring",
	"blue joy ring",
	"gold joy ring",
	"green joy ring",
	"discovery ring",
	"rang ring L-2",
	"octo ring",
	"moblin ring",
	"like-like ring",
	"subrosian ring",
	"first gen ring",
	"spin ring",
	"bombproof ring",
	"energy ring",
	"dbl. edged ring",
	"GBA nature ring",
	"slayer's ring",
	"rupee ring",
	"victory ring",
	"sign ring",
	"100th ring",
	"whisp ring",
	"gasha ring",
	"peace ring",
	"zora ring",
	"fist ring",
	"whimsical ring",
	"protection ring",
}
