// Code generated by "esc -o embed.go hints/ logic/"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/hints/ages_areas.yaml": {
		name:    "ages_areas.yaml",
		local:   "hints/ages_areas.yaml",
		size:    3795,
		modtime: 1563912557,
		compressed: `
H4sIAAAAAAAC/2yXS2/jthPA7/4Uc8tljf8/cRwHvXW3m22BIljEQRftbUSNJdYURxhS1jqfvuBDL9sX
w/MjOcN5kBz92hT6zsF3NKjol9UaMIE2AlA1OX9FvRCt1iDkVEdg8Szd6kuQyHr4wxm0ZVClBqQjGpbV
uizJgucjnkHhKbAkFNwUS6Lk7DyaJWzZD6CzJcmlodUaem3KPLvChla/0bGDFxZyPuysDOIhilETEEY3
r3hPV9yxKTXJBY2+vaAWTe4OfjCXLhg6DKQPJIcz7QP4AO+6iUEv0BhmC1V3vnNQ6YO/gl1bCZbB5xjv
Owc1dy7IzqN4baus/U86kYH76OY9FOioIeuzxM6lf0rYOWEsRzkFWpibREJIwJMIKkqkqrXVUAq3SWZL
66Lznu1YJ+V9ys4k+p5vTOrpUnmvS0rWkwMP0YGH0YFp9YwNe3mIpUPlXOXD6O0DKDYso28PYLCMdTOp
bLgw2s4UZtAa9AeWvE64pZka59F3BG338WGyTV/33LTgajKHBfGdtWSyc5vo3AY+37+MpbcBlIbduIXN
uP8NFKLLajqNgXSuhoLIm2lDG1BsT3RmgYKMn/NFtjfQ6Ear2XjDpmRpZrZbNg5OrNXCqtM/14VhdZzN
zEGYgGdR9aIYH6O7j6NDjzkhXptp4SOorphZe4SDFudvgFyqrtde1WnEoFQEB8Mss3QEfsJlRT5Coy0p
lAVzpNiWN1W7Bo1Zqk5ebaNXWyhMqAGqJn3b0dMtlCjHMdJbKDU20dI0l87k5rLRR1qHnznk3swc24JQ
eWkzJOeqIrfgayG6OdDzBU5+PUW/nkYfnqANV8HyDGV45U7mLbO5gvH0XELXEso19WgO7K54rz8+hIul
GiEXLoO312+3cEHYXGjKI6rGcCZvDnW3bdzyNw9deZe5a7W1JLeGTlpocVB2MfQ72LzMb7LdmIrw7yfN
zO9AoaX/Ddua0rsDJVjMJ96aczDc05TUHdRoTB/e3WmdoUOIu62S2Girw3bmU1p2fn1jaTh4+e2fUdFV
Pdfo2kWt70LytUyqUmieY2ie4f5lmvocL9DXHwuyWUx4/QrOoKcF+3HN9jfm7W/MKwyWoQHCdkkvr4Dn
MWfPV9fSc35JZ5Mb/FiYcSiK2xqrzi1wOhZJiLdnejHP1iJ80f4cgmSipLSfctHgsRvarwbDA9EasvMe
oub2E9xv/w/StURuRJuRvHadhd91VYd8xubGBlIPJLVkb2xM6EXewoMVWxtdQYG2Sn3YOvV4FQtbqAnL
2EYdCD1UEn7Ts7ta5ynjeUvtXoKuZo4NT4XGkJyHgeCPLsNAa9LRSc/m69fUzOVjN/L4hmbNifRD4xdI
9iSNpG4o972LkZ6mER+eoaBBvIP7S/AQQGji0rP0b6fV1MPmfuNI1C6DCJ/RxUjmiKBVc1dm9BP02tdg
yPvYn6YhMmWU4pUcWpwnIOslLJgigW4qvxlqcUZyLtxAkyvJyAljGSUkoUEoRLsj+dWeMHS6rwxv5Dux
wROXmGWQyIZJe8/SxNJqtaDXaEFh6zEWRF7k4py0hz13voZY/VFtFFP5x4Sk8X3NQtO4CyKUWvxqf24a
8nIej44bQDw9hbCvY+yWPOp+R9M5+E54jBv2UWyDOAbS8/FIoXdX3LTstNdsV+81wWeD6gjv4e6NRySK
Pl7FPcuRZPU3GwPfBE90RkkfUzWd0Nw50PZENqqaQZ8sVmFFLqhcktWgBFqm1T8sCHvC9HGiXU0SVOY7
OhW+0YWgnIc0j+JYch9BiSMcPI1K/9LGYDry40ePYpw1cMdQ0mHtoCJc3MlkFC8+OSM7Ja2XxgecfQzs
zoFQj1Ku/gsAAP//IxoMD9MOAAA=
`,
	},

	"/hints/ages_items.yaml": {
		name:    "ages_items.yaml",
		local:   "hints/ages_items.yaml",
		size:    830,
		modtime: 1563912710,
		compressed: `
H4sIAAAAAAAC/2SSwY7UMAxA7/kKSxy4cFhx7I0Z7ewuDLCaIg7c3MQzDU3jykln1P165CRiF3Gp/J4T
200y8DzAOfCNpAOEneKhILyDyBkEo+PZv5ADHyERJo7JDMwT8Fk5pA7ySLBrqldlBkFLgbIWfS7lds2Y
QTiPJEDzEGhum5u7L85YjFQTe4xUqvKM4tHYka4YQHihDvYVTryQscK3CBNtbV/BL7SZM3rZYOGb0188
FHouZM6E2rWDE9v3CQ4VzYWFIwTKuR7KsUQ6xVPMwm612XNsy66Y2qgPhX9ioppCR12V6MhcBK+0objX
GR/+Kp1zRFmqf0RZtNunCyXjU8DowI4oepgRnqrYqzABrwi/V2+pg6PGnzU2wQ+Csr22OjahjWaSGf2b
Ob42oUkODv5b8D24fxYJ2wkG8WnSCz4p7SoZWRei9AE+3t11+oFTEe0xLUKJYn77kpJVkYhc8PGix90X
0zdjNAVpZC63oeNoCvpqTAqYqWzTwKSbz3aEkXkqsuIj82QyT7gBbTRgCLXSj6LuqzJ5jR7imltO6dua
zQsLQrIY2j3/Uu6VzZ8AAAD//1EUG+o+AwAA
`,
	},

	"/hints/common_items.yaml": {
		name:    "common_items.yaml",
		local:   "hints/common_items.yaml",
		size:    2742,
		modtime: 1563912710,
		compressed: `
H4sIAAAAAAAC/2yWT3PbNhOH7/gUmMkhlzfvyNTkoluc2Eo7dquKmXamN4hckahJLguAVtVP39ld/gEo
XWzt83sILggQ0gfdWl/oAtsWO20DtF6dsD35/+mHzU4/0kd1QmzBma7aaaMfp0KVtrXB2Y9en5shwE5/
m8EzAQXtCZwODkB7gNLv9BOTnAp1bmzfg/M7/Sc6wxcJUJVpILlsT0CuqoyvDXNqZs8VJaoG44IusAvG
duAo/c7o64SUddhpX1to6OJO/0R1zrVqEX29TOV1LGUi7dUHcNekp9eRSVs9VMYPPjEOIxsNCwVoPGtu
lNo7TIT7VM4Wb9elg+NYSgdTWDX4Dn5J91wrb0JRQ0Oj0t10LrXyBXQhaSpnIi35Gt/polCDzvmz8hd0
/GRz+qAuiCVEz2x6WuqDdkMP4JX8k93ysNHHlGabnc5u6Haz09sb+nmz059v6MOGB5453dl2lVcPm02o
+bNMQOqj7Sq1f/yiOxMGB1FO8BeBsxRsu1Z+EGLBuBYdp/rl04MYX5gdR5Yq2R0lS5XtHWWrTo3xIWrj
kWvu4dQMoGtsrkk8gP5ObFH+whvjZ4yFZije1sYLsUVZpRIgvbAffRxOaBZ6h3heGcJYKWrjqnj4rwIk
HJyHMg4FcFiemv9rKKtE+EbwiaFI1hf4Tm9i5MyMFejAVXH+JEDCf3pwIZni04RYOFvng66gi4xnZnvo
JiVZwGc7rd/ZWehKX9s+jhfIkhxp0TbkWiJsytXi7gnNi8vCanHZWBa3cgDdehPtGS67SKTVnZgtt+Jy
fS+G65utc47kgE7fJzmh5/cpUbI7SqYaW9XrUV6YzaMkSnZHoVHe4BP9iVp9IUZ/pN3W9A0k2+J1JBLj
qbHxTF8FcIhFwCj6lUoOejBFfM8D12Mk3xZxKERivMD6NDowm+edKNkdJUuV7R1lq3qHAYpgMZ7cYYHc
zd+DLd686eIX87eZsUI/EVb9HgnN7cZCditkykG53rZHKKNNS0K6ZSmfNyzFq+1K+bJZXXKwHKcTxWGR
rPuRa4noSyiOuObI2yp+YjmVEjTmujpD8wmJ0OHF1xiPm09IhD7ZaXk/7TMfwJTn9Nsjn5kow8mhtyYZ
YGaiXGzbrjucGSsBfZz+oJKDd1sETM7e30fC8aW2rbeFaSLhj5lNiu/T2I8H47/o4nORfiZK8F8AAAD/
/3DP/VO2CgAA
`,
	},

	"/hints/seasons_areas.yaml": {
		name:    "seasons_areas.yaml",
		local:   "hints/seasons_areas.yaml",
		size:    3476,
		modtime: 1563912858,
		compressed: `
H4sIAAAAAAAC/3RXS4/bOBK++1fUrS/u7LYfbWOP20k2wCbBYBxMn0tSWSJMsjR82LB//YCkRFF25yZ+
VSS/erL0Ba0jo+HgK28q+5/FM9AA2QQtgTXUUhyPiy9XaiVaC9/xREG1MVegEZR4omXcDTWe6WPxhSbx
nQhrw9ZCZUTT0uJ/bFjDD/baodDhsroLe4WGNorUIFo83wH5pF44u/hGhp8svOE5Mf43nOiazkpL43ui
ErAXNs0AfGPJjfEK/pAjCzwTWPauAz6CMvYTGO/l4hlYNqBQB4bOEHXsLS2+RWp/CSmxjQS6CJwTAIcv
+eY7wftvBJaoiecvnkHhyedvUhWZJwu24x5eHpDVA7JePMePJbxsBzfYDK0ekHVGvtOZJLxEd75AhZYU
aTesJNen597bTugWDLMacLZ2+PLOhYwaHf4CR8lsVMy6YkfLRlyx1JN0nmkYFPKC11LFOpRHth9BjeF+
oL6K1FdQSWyK0K8yyxVIOjo4GlZA2hnUNSVccSWFLvf07MqlYSnJzJGeHtaRTVzaXhiUpYIjY7Ae9yTK
60h5DRWrihq4oCy2rDPxNbQCtRssG121BiWUqMsNimXDRpXQ317UJ4u6GQkk+N6gNTiDqmcpNJXoBcv4
reHGcmbBJlqwyVQ3UBusT9Sk+OedG2jQnMqlCBXXs0tLhbfi3g1oNqkWy0BtoGeW45eD3t9ucpAU1m3A
sam78rjBjJy9ifw2kt8CGlVm13aW/dts2xZqNK7Ua0XV8L8mn0QwJlmxVthqclDNgrsNGaJ1GYLtQ9Js
c5qPftt+mEav0Y5XePkaG3VeFD55hdXXezsjFk0osaTUoZRpXRGqgsFrdscr1OYaCIbU6QsFsjX2VACl
B8YSec0OiKFO0FmYuWW7aNkO/rv6mnfuBopT9HcfF9AuU90FCl6T9aV0nnO7olQK0Ii2c/eJuAvkT7PN
Dz1qBxdxuxmuZmohV1KvHCzcRwv34c2QeC464z68FvfQXQT32cJ9rC/tXSmk69SS9tB2bN1wwoR2aJoO
XYGU0RpjuIeepYUzi5rKG2wfqnoGBL9M2x6yfA+uM0SB22jIj9R9/0/UB2cMzfhE1C9+uE/w5uuao5fE
ORRwaBrA3lnREHzehB3uE9RBawm9RHeMLTBNI4XIoWT9ZEeJ7WM7qFCjxvTe/kR38+EmHT7AUCt4Gjxi
D1n8jI0pDgBBswoTBENvxI3GOSL3rs/hwU6r9NxPz3w65uArw1ZgOMkO30sIjy01mWfGuSd9j2poQlKO
9TrBVgnXXRcHVGgRPpMl4+I1CWgikMMyR3vhFoc4DJUEW0Po4OiNTj1lvAsUmhO5JbyEQc6R+ki20s1v
ZVvXPcgsYYhvCY2zUuacbb0I2YzJdAhPBBwuqGIyhVeoadFRzKc4JqURLiRA0LRBc8qJCZpidfD6RBre
hLvOJtZhuAkvmZny6h4NkSHdfiAydEHTREviBbVw19kkWOBLsF6pUEjhll9oFPzphY6jvQx1fWFuQidw
QWSCaHbUBC/B64ZMEvzqCH6R6iWFfD0QWk5nugzaBAaML2QChN55pUskFdMMiXRL5CJ0KKB3Sj8ib4zW
DSVUn8IzY93T1Nsug1od1JZBXLzod0Khh6C+ByeEu97jXXmyz91ilePHGhz3sUpXcRyX8lokx2U8KbGe
+fJOlhJ/iP6DLCR+lP0TAAD//4VEihKUDQAA
`,
	},

	"/hints/seasons_items.yaml": {
		name:    "seasons_items.yaml",
		local:   "hints/seasons_items.yaml",
		size:    813,
		modtime: 1563912710,
		compressed: `
H4sIAAAAAAAC/1ySMW/bPhDFd36KAzJ4+WfIkEXb3y2coIVRQyrQTgVO0rOkliKVO7Kuv31BUkqcbnc/
3uM9PpBjiLOrKIyg2vfkz/R/Rqa1EeQFFe1T9UVgWuEOFqGMn/wFQvuVmV548I5+4VqOP5b+M67mDA4j
pCKm2nc7pUMB5my97wcOeJMdXlFWem93WmwcSp2MDI7Fon9TPa0gaUaWviieU5XmZx4cAg3W/4YWxTGj
qaOnDM3MGiA7pcXyS8Q2tMJThmbG3Oa+Y+nTc44b+MDSm+UqPE89/cQFdg1pRZ8SMsICWsDdSBq8Q7ri
NKFDyv0ZLMEIVvM1ineZ2ta7nF2ujPjo3u2oM1g3xAXQ/+ihogeqU0N35HygRaBwgSZHPEBfBx8reiyD
Snf0w0jUcKUWdrs893tYa9RObtDRh2Sm2Rqji0xuePeFmozWE2rZseMsKmCfgdGXmPK4eUlTSHmKBpYS
BVMTWO6bkZc1FI3znD7U7c6MTBCwRgHNvJTzrxs58mIukwv/CL9lZP7ca7n/xs/3bWdx9DcAAP//RjxA
fC0DAAA=
`,
	},

	"/logic/README.md": {
		name:    "README.md",
		local:   "logic/README.md",
		size:    993,
		modtime: 1563912777,
		compressed: `
H4sIAAAAAAAC/3STT2vcShDE7/oUhd/BXliLd3yYh8E559/BOYQQUHvU2hkYdSvTrThKyHcPM+u1yYKP
u6Lr11NV/Q+0UMhs14Vk1Dn95IIh6yGFAaLO1nX3kY0xpcyGkackjKtZzaHTDh4ZYyocnEccCi0RHskv
DavxiEkLXpS7JtzjPnJhUGF4LMzwbWGDThAd+abrrnEnGEjGof2Dq+HL/wsVFr/t+/7rsD9ieaI1+w7J
4GVlpGkC5VyFkhuOE9bhSCor9/ggjMfkEaKn76fx/gmr5Zmq5QZ/k89gsp3BXsTwGmuibEcYhqCr+DOu
/arEOcntHifwOfUFhyuvTnbAvJrjgcE/KHjeoMI7RDKQIzOZgxC4OCWBrPMDl7r4aavHmEJsLlE27fD0
hO7ivqx8gQMLF8p5w8wk1gJuCbS9k6EwhUgPmZEEhLgt6pE9Bco40MwwJ6+CH9VZPFHG57t3b3FQD5Gs
Jf6eZjYElbpjkgOCzjMZhHmEa3uchKy1VUnwba3lRJrqIhtoWZhKw3c4jl4bL1So9jIn8+a4mYZEnr7X
9hXarIU87E9J7F7DDb9+D2ewDtDVLY0MeiJ0n+qh6FpgCwW2Vv8kI4uTJ5U9SEaMKpdei6qPyEnYkFUO
XKqvgv/+7UKkQsG5WI83vKmMzfLW+uPdNAHZYF5S8IqZyb26VtZ6pkmwZArcd38CAAD//yw6337hAwAA
`,
	},

	"/logic/ages_dungeons.yaml": {
		name:    "ages_dungeons.yaml",
		local:   "logic/ages_dungeons.yaml",
		size:    12270,
		modtime: 1563912611,
		compressed: `
H4sIAAAAAAAC/7xaTW/cOJO+61fUog8zA7Rn1m572shts5vsLYcNFjkYfWCL1S3GFCmQlHucxfz3BT9F
ilLbeV/gzWEwbpHFp74eVpW0AXrboDCogN5+gP+T6gM8Hf5umg38Ozzjq27oLSDRBgwqRVr8AE9x+Rae
GeegL8y0HXRSPh/s6nPHBAOq5PABnma73YJWSa2VJFSvLnjVhnBQUvb1ki1gf0QFGpHqLRwVkue4xW2/
4Apcv3SQxi0bpIG2Q23W1jQbuEs2uDCKGaBJyS20chRWyN0W6C3onnButx3cKeYib46jMVKkw3Jpbo0U
+Oaao9R69nsEexx1B5qc0J1vF9rjg3eGsR+emYAOCXUqDdKgMIxw/go7px5c/oAXIhjnBJQcDdrz/vfG
K+sjogEAmJl26358C5EDcWZEGG8zv8v+i2bbzc12+NspTDT2KIIxPJzC9U4behej924xevXAnpHCEdFw
1CAv/AM89a/aoHqNERQFHBp6B0fZH5HW4XMXoz0XuHXLtdvYyyNnIsb99V3uNyFVbyN25pO7FZ94ifoi
S/nOnE7vp6WTTkhMh+pQRuldYW6n9mTt7KCU4VIOh+bIR4QLE+dlM2ZSnEjTXWQ/gBmFQLt85bnukJ/K
x5lSAf8Wnjqi6BZaInDrHw14JnrUoIlpO+TRFzOFEhFl4pNVioUx9XysLywPJ2yhYwY4vqCCk5I99Exg
S5Sp/boL9JGiY+DEnKTqVwBti6QovGSjxGZVEMSEkUClVBfyugVtiKAgBXgW2cKoMedli0AbYkaEYfzx
g6M/fwYqM/vRBj9HEw0erJ+J3Ho4KLB3MdRs4D5pq+SQyHKeCbmIqO19pS29A04oRTWn6LvkhZ8R12zg
IaFrJZcqcfnMMpOUh0qK5dAYtmspMAn3GRHYOHCL5/DVVSGyY5gRRT12uosst1u+o3cwSK7hRbIW5xbb
TSy1g9vPliGEQFUscCKdQXvJqY0FiCFwcPu+xhvW4s/FHJqTHFV8usKwsx10B5/W5OVgg2NiBme7nFVu
rfLNBl7laMMUWs4GnximQzhy2T5rQCHHcwdGuqw1HdOpvLgw05VZsoNvGa7JPBZLigO77EsJP+3KUogI
rz7oTkrjFZM9KiLOS/lkc0gbKRC05JShWjdlCYWoXurMRt+yWmgHmv114yyxvKIongKcGGH6Iqucz1QI
N3EgX6e3bi2PJj5OyOMPtUmGUbQdyON3bI299nfwsYjQPPKc7p+Kv74Uf828sKSbs0lZfxZH+udSvOCr
VHBEbhJPzC1rpGq7qV4rxISECiaKyganJ7P43w8+wY6K0TPm8t4XVN/HfoDdVFWFQxwjaHOjx6MtZaQq
2TEPoqxImEsJbDSF7XQvGEtZionzIdtWX9uzS/oQtLW2sjX9guU8rSfY13RPWSQtUR5g46SA5kR3YDrl
Mr+VSqByRVZuD7A3puNde4sClSCkAYUnVChaBCQ2MK0STWXLsireTWJiSXxVpcO0Knf6FQc1hW2Dx6P2
0Xm+bs7AFCifFgLiqrTZodfYrHC/l1P8lIQERnH3mw/cu3plWl10eYFa/B8FJR7mAVgZKmewxePycmfF
B+7fP+m4KzaMzgu3byTr8kauXHiI/vZpNIVhCkpbUzRzi8bTg03jnyWhp+TKOT0UertUdbhGz/cas3pv
d61Am1+pRfm4g571rM2Id35KUWhf8Zkrne5j6XS/XDrdw4kpXY0C7jO7FadlZe9Sn1Jc6VZ6Ox4zWi9O
yxqRVM7Q+9RPwH/kcKYegd4XJUASObvFnwpR7yHSPBwLIBn8TOLUBxWzkmzNxyt7pgqzdGeTzwbuZto6
WBpbKeh1fT/+tL5ZXGdy/rOSWwRxhc0X9obxqWzNpWWoAhkusVyEeSYc01/zu3kpMe9rBf6rglDky/2s
xzQdaoQLkkEKDUQhnKw+HVoJzHLK1l2U7hdPTO48L+XE7V06tZg5jti3VRYoGGJmAV8fumxL/RC9B07U
Gd84rRxL3ieeXNrtDLFAmAFhVgFlgMq20op9IcVQceWovL+8r+jqIdLVwzJdPUTFMnJ4mBGi22YTzS+d
4j21dAcryM1zBjxPgCfhbgEl6jnR8PTMJ3GUvbG91y/GjRwGaTR0qHAyoZ8fFD7Oi8s1ag0QOXvGG/uf
JYyZoyZAYP2EtNa5SqBp5jLNlN5fczh4+Ip6EdkK8TTZ8dX4KuEpO76yhlhSdKko91pFnOYib6r5Tw43
Tb2jNSKYn+1nbSVeWTqv9/4hO8fczSGHn/3YJEaZPT6/ix5mzV4uYJrqVdXfnRM/L+SyeA6K+QrzUOpf
tfU2kxjp3Z01xcoEbMZVGak82C4G8brvPKKcVR7KW+nBTQGuyphVhoX3r0pWSOcUkiu2EK7r4lolLwLo
KM4oxcr0Y3aiwyAvvFBrtsKy6p+RVf+EQaF2g+7ErtMj15HmrGt/2Sbu9SvK+WGxOQuqhVdjYfuF/fih
5LGa00UR+XgzzpLj3kFK/sa+IrVOnA0DKu0kyAEFXAjnb+0Ng4mGIg5wIWZ9GJUJnUDaquwk9RrOHOBi
jZ1CZTZPSraNhUA4z02bUwBmkLbQo+oJo6BH5iPBQwildsSbxk0OzgyuT6+JI6YyPG6PITyNLpNgJCpH
lh83BxcfV1RxbVuYu83owwPfpaiN9DmXFB557MuXVV7szvX1FUvIpyJL/E+VKvMc3NYJEnYuvECYdmVd
VwjvzCu5xPfeXoHGD028iejYGrbKQQswa/C5++ar58V7vrkjgv7LNJ8u6jgrWS3Mq6yN/9Zv721+/7u7
vNC0bIwXLJBoqRrglC13RgdBRIjw9RxaPO7tbn7adUTSL1JcjOySh+pyanLg0+KI5K4AWQyiiqwLWc7H
9hkMavNmzObIF3O8PrLZgBT8FfSoDWGCHPnUIrrNrkm0DM7E2bWGNtQLKvifL/+95OsCzESyVQe20EXk
ndh79cijryNCIH+3B6sY/KnTXphajPUiUN8nd2GE8NeAyvziK/+QDnVNSffNBjiSFybOfzhto7NixfXr
cTSuueeSUPuQwIlx/A0sBqPdWlcNuAEO/92NC5gGpkFgi1oT9QpGQk+eMXzEINUzyNESPRMt+nn6hWlM
7+yoIkxYyc0ml+3ezcnRwBmNsVDCazwn1UhQeLL1AjP/ZvcqhO+jNkAUil9Ms4mrnVX1dKpFLOQFTEdM
0hqFUUS06Kcdiggqe/bDlh/5RRua3CMC0XrskTYbe2P2UuHvzjDtqJR11GkU7u4gnJlXaxp32BGtEkzA
KCgqr6jlHB0VbTblcUyDfIZfreQz6RFIa7Trhp3lOvKCwIxFcCGvv23Bes4+SBYgnMsLUmsrPaqT+2zK
+8Auu8iRU28zyhDYyf1KGf09FsP75enD3n9fMs+afbg4itLEjT0o0L1NhT20ihzX9rnibzLNFp58XNgF
eR3sJcWyItX8k7SynthbCBec1+r7qS7eApfiHBglDWPPklMUwDTHq18MvUdty5jqQl5r1ac8zjBkimdj
iXQfpXo+mEKxc2fcNzmWV+anBePFFwjTgauA0xAUbrI35wGTT5gmIlzWJQrbzk/JeW0/u9C+k+OY+kQp
+5VLLBzsND/KvzArkvNHg7T5w4mon9cRYq38RxVR0/rMN26iMo1ZCxO1nZQaXRGd0VgTrVEEXy4yG8Xu
y8tjD7vP2WdoyUn2CcdT8vr0YOBE90QxUUVt6utzIbEr2GdNwLQgm0LsoSOc5zE8OTnv5vfz1mCfBMTh
8eSQOlbrkvbaILYYFGeft+2XLOlem72txH5JCfoYOfFxkRNdjYBEXf+48PHQ0Ee4/TyngcfUNMY3QHAD
pLW3KXy8/Ww3+U9N6330MW89yyLSl0tVN1fP3ubfJISpmz334+1n+PJt8liBJJuyTYC/fooFjd1fj5cL
CWWp+1i6zO4mFMEoMuT7S5luoSaqlUNHzqNeX7mFwV0EZy5f0G/zQ4plsXmOK/clQAxgu7UnP/DaUbFm
zXK7Uu/LN9CcmELOJNcv+XRtSdb4TYlTfB1LRMtsjlg0eo0RqnO863ef106d29G96orvCBYBumVfF5RJ
W73DAx09ZnSULyoM6mSVL2Aeq/dBtWdytqpc8vXbdXvXY+JaTHPkxDZizkiLfNCT59H9/6GhUlic6Zeq
fV7ue0N4Ff1PIBHY+P+xlWZLNII82YykqGyH1jf/HwAA///x/Tv+7i8AAA==
`,
	},

	"/logic/ages_items.yaml": {
		name:    "ages_items.yaml",
		local:   "logic/ages_items.yaml",
		size:    2010,
		modtime: 1563912660,
		compressed: `
H4sIAAAAAAAC/3SUv27kOAzGez0FkRRpjEWSwTVT79XbXBeokG2OrY0k+kg5c4PDvPtC/qNIzm5J8keZ
3yfKMlp0/Rn+Jz7D25WoxwBrsgHLtAf6rlRLvpUdVQAAbw9LroGX54cGlnzLaN6hnWVs4OLmiA3ISB/o
tG7WntFwv8H9K7Qk0sBA66eIog0DDMY55JvW6bNsu/fbk6yn7Z/Xd9VbbyPb31Q8kYy/yVdxdWwDh9Ma
qA5JczzCPz++/zhDHK2AFTDQz76FyZkOR3I9MlyIYQ7ROgh4hYt1LoGeGKHHD3Q0Ya94nhCzjw9r2MDr
c/LwM35Z4hz+9fywGdjRHOIZ3l6LaoJ1k0unY+Pu+n4Vixz8b0KOTwKcPO9MgJ5AyGOSGAaBOJoIFysx
E0+xAaFsQdIbR1SP4OiKEqEj7ylAj4G8DSYSf1PTHLoRqP2JXdxV50Obegp933AM6G87vQ2fm/TXLvUI
E9PAKGI/UFSg1iHIlTgtd2HZktJ35SgMMBK9H8s2duNS0HeF3UjLVe3ESwOj4UnfVTczY4hSt29FM1Rd
p1yY6IoMg6MPrBtbNh06jGl7kb2xPchsYw1dnJ0mZNkfI/yc/QSvyU80cUTentWEg5FZQEzsRnT59pfH
qrVWS9+p7Du06OL8xG0X8Ad6P1kpQezBRvT71WViqSwPHDnNj75FXrJyhrc1ioy4prR6hBvNy1IaJwQD
RpAOQ1zrcGHywMYzde8NtHNMewiM/86W0aeL2ZaTBMFwWlEDMif3MAJd/oQjfD8BBZRvqvhcVrOkPsfM
zvYn+Bs6vkk0u9bkQnpo2atN6h6XYgfjMANLUFb9TSLyLQN7XDK7n6vd2dFtynyrm6ZMFRoL6nC95UYd
yHXwjH3qKJg8fsYqQQW5i1i35IuIcoN2JRmtlVRoHj7DRzkVvorIbKWpArOMzB6FVbgJtyqThi7C9edO
X2WXwg6Dl7NV39Za/QoAAP//NyPyKdoHAAA=
`,
	},

	"/logic/ages_kill.yaml": {
		name:    "ages_kill.yaml",
		local:   "logic/ages_kill.yaml",
		size:    2246,
		modtime: 1563912660,
		compressed: `
H4sIAAAAAAAC/7RVsZKsNhDM+YquuuAS6gUOL/ZfXBEINAvyCg2lEbtev9p/dwkBJ7H46hJnCFBPT0+3
1HpSV3T+IUHZD/xm/4FPubPXNVoeW6nRetWRpVCDxpY8hEhLDfp7Ih/eBd64vnlWCWnisKF87ZO7Cd2A
gflaw3FrCUuJ5llVb+D2ZngW+0AYjICdfeDO/hofIUE5rbwGORoNSTXNMiyLx852MGR1HR/4RrZGqs48
kleurzFRr2QWyMAcyDdNqjs7a64E4yCkhJ3USAjQTOLeAwYTYOlGXn5V+/NBpEIT6ciFbTE+JJB/rMsK
AJRLy43KQZqc8+y6Adz+RV1ontUblNMJCRfPI0bjqFM+QPOBKRwHyOwJ5pIUNYKWOjULVW8IA4EdSdY3
lCcM7M0/7IKyS6n1t/iX6knw5x8R5kY+mE7ZTI6SzkGc1373FpvngpH6PzdersE3Qi/KlmL/WOiCBeIb
0rt/E4sfz2zhsdvCke8fKRvJbhc7B4JZjGVcZ2dNGgN5ghjXEUzM0mJ+dVPGqpiSOCMeCZNVHcmvNWNt
jICoC33g91I0164kt0dwbaYQsVcxiGsonhn4YRynkLEpUaEbyOJOamIXN6QX9RerouDnoCJews6jkpjE
56ZpmmrllOEW+r8C/ydYFH5kCdvxsVj9NltHfhE4cHS6RPVplOpqrIVjP76chWWrNUqKNTrlaHPscjo1
zxztYK3j7s+0fdd22zw7Tf6uwsupcwQ4KZxNbducESqmGme5fOuNcgH9YJw59VaS+TQHGYN90Ov/Sbq9
qWkep6txGEjp/Jp4KVdAns17I3Jebhm+TOZKGi1RsCRxTO8BLSVs0riwTxHzy1m4Spdv2sTL07KXTC/X
iusJUFxK6UZZP73o+SNT5YNqvqbLPP0vM0r4I1vNfjzargR/4VeWSHJ8ZwWZ20Deb5n4ur3PTp4i5Lnh
m+rfAAAA//+gHDYHxggAAA==
`,
	},

	"/logic/holodrum.yaml": {
		name:    "holodrum.yaml",
		local:   "logic/holodrum.yaml",
		size:    15100,
		modtime: 1563912858,
		compressed: `
H4sIAAAAAAAC/7w7TXfsJrJ7fkWdeOGNnl+u703yntczv2AWs+ijBS3RLcUIFEDuODn+73MAIRUIpL5O
znhjdasoivquovoBVN+8vlfQ9kNvVF8BFS0MUuoOFLswBUYCbRqmdS+uYDqpGVDRD5RDI4eRil4KTR6g
F2A61itome6vghrWgmJX+xZO7On6FHawkHoSr0xA05v3+gl+f9Rw4ZNhMDDqkJ2Z3YyeObPbN5Rzizzs
2wu4MsEU5U+EaEOVeYFTDQ8wUsWEgYtUIGTLNChGm86hOb9Dyy504oZ0VLUv8KdUdtUHIQ/QSSUFvPWc
0ysj0acA6Lap7B5SGUdDw6eWtZaYhmoGWg7MdJbspqPiyjQBADix33sT458xVODwdr0Bzt6YquBkCavg
12kY4ee6rusPMtDXCYxizEJiJBXom1RtHRMLmrG2BG9f9YYNlSPMb07VG9PGrVg0IAhjIeisGH2F86S7
uk43/Nc/oemYNtv9znI46w34v0vgjh6/0zDpTkk5bCiqa6I7OVbw/COoaWRMr4LxnwPA1yOALz9tIRwJ
bDgz5ZilFwboTr4xbg8/uNeP2n41wpcXOC3fNA70u3E8/w04vn4KB3mAG9OGKQGNpNqQM6fNK5wZ1cbi
ycpp1Z0ZOe/FVXfSLBsM7xbn+/qmrv2q5YWn57XnHAbJW6mGmrQ/AhNGUdFsVLcmY6+oYaC7fnyBk//0
qOHMOK9gftnJSbOauJOANtOwgrqFs0LOnLkwajprc5bmuibtL3h7vGw9sLPLr1XMtOBUQE/DwJQHd4aP
KKnmt4ET3qE4QRTRjaoX1xXdfZvmoehkpkGUSPPE+O0CwnmJ9UEkwllZ9Wi6RTkQpzaQvfBCScHIA1gV
s5B6Ok/qrMn8P/haeADT9Rp67b2+YhS0nEwH8uK+GaXk1qNr+aqotQJ7FO9vE7eCTGBmvvfICQWLT0a+
bga/0F69w0VOwtBeBMtKlgdW33phLP/m/wvLL7wfR6Z0BYvmubC7+tqNq6s/SLx14I4nC0XQdZtd2hYZ
z/+vlDPQ1DSd9QdVQOsW/VePOcgz7wUoSdv4jH+B9ehAK58Qfesu9g8Bldi1DzubTWqPOdjZGoOJJcLD
QqkQhYfSTY5f3b8yPmjtE49Ocm7FFiwYyQj5sJuUrbZG6XctyoI0zrtySBa8FGTsdggOclGlWYXyvipY
a0HCB4c/hkskW4LDjjNhjrxxy8g4ChYYs12NM7vCok/keDb0PePQV0SN8jPrHSu8nnKz4NDAhE24UYYN
DyCkCd/buBCAQVHRyg2KFziVsKKDtc+gpLxU7unMact8WLJOnDaMM1N78ixUoCbFO6tN8dgBVWKmJcUP
Ohl5PWdQjjSQAowc7cJ/PK9HqElD3xjIyei+Zf5ViaL1/EfJMgJt6MgqGOhVMANXLt+Yru8w4+CqTuEh
0LvV7gq+aAP2GEVnMedfMWtwxAVNL+wOskqe+Ugom2zp4NjBlkli7JUVY8P7y+UFBcxYUxDbQxUlh7Ov
7Z7rHVnc66W3AngWbU4Ac8K7+MWVjq++COgkl62aBhg57QW5dlQb/h5yaG82QirTgb7RYc6IT2cLLB81
XN+HNKmeOwreX69pJ6IBZVnJ/kkMWeO4y/88BemR8pqfGAryWpaLNoN02Lau+4Pgw8UpScSdZJ/8+Rf5
/P3nzOY4cdw7CWr+mGBUtFc9qzYMmt+r3nUglhMkG0fboWU3q6ycilXLfN8AczzSt3qh2WuUz9ZxJbJ1
uKdC6Dlmz7KZYcPIGSg20F5o4PJmI6rfdSZthrw6goYlHQnYrVZEJKNwHJvCZ2KwxwCj6v/YIgyNC6dV
QRtjL/pBJG9hoMJ14RRjIW3LWWmZXz4MLZXWoPQTqGniG0QLV/wKzxgb1L4UQT8XuAo2swSm2BxXE7Z+
Ddk4Qf7rJWvEe7sl8QO8W5+N3HVKcYMKeRasJNiDfkpHLlzK9mrL6FfGRtfqCVKOcC8Nxe2SfApaQryc
ZW6m5HdBgS/C9I6ONrIr1ZNe65pSNGotVV5IyOnmnDWO5WVnXn6Ps6kTOmfoh8S1xeKk6w+CHHRSkW+w
3OG58Zrl9Gk8jdckOv+JEJfGrUMyv8+N4D4LpmLtsYT0/CMylzl5wREQtcvKQkzYGAfUqNcWBY5sPlqT
9iuuhzKqUdbGpc1n3Q+OFv8L7J1dOdUaOH1lxJZD+H2MJ066EgiU8+beB4XNvZsZkwQynOZlW2ilyi+r
G4tsP5O2HW3lO3eYk4tO7XM0DUOuV+Wt6w7c/kJml6f1B2m/YL25CqpssWsdIWAn8Yn0rpwqbRjl+rXJ
OV7gz9USjvgUyozE8X2Q9qecqnxeIiUXdCpzGV2NHXCm1H2Mg3VCw97G4f9WjbwNLCEwk4M63iHVCJys
vjsbWtKeHctPesFl+XyKR0hOm9vCOH1fQ6ZVyoiECmijpNZwVn17ZYW7QJdlzU29qCzZc3unnP9z3PZ0
2BCb0GIL7hB6VtFkqvlgIickzmpHxQv73di632FzJJM9F5V+16w9RZmu8H1qgEu/lUkbrN/DGhsibRFJ
ogo1um63oWotT9GVfVJ9ojdz58Nmsi9z5ZhLNr/VOG9FDi0pl/GcQkW2BXMU/GJT2d6mr4ToW2/Z8Khh
brlHuFFVvYM/vqNfohkqtQPz3BDGYnQ3alZe/oX0Lmo6REwJXtqNViAwgp5jAly9Dc3UNDLnYyPz27t/
yV5pfdctUtpmKyfAn2yxxGvX/kbabKmSBCWF9jl+rEe4sIpZ8fe0bmy+jriPy9tIG+4ub3FwQ9VOQfXy
sl/umGbol1w/LMU0SzU3EYCsdGe3uiaDUyForVzdvATlnAkXz5ZZKjekU9phi0Oxm5tNWhF4gEcNI6e/
TbYmjxjt9H4pnPJXneUG+/FVZl3PFxe9gPS8c8icJWltHZkxQc/B1l0yMpgn/21IRI6vae8hs9C+W318
mHuxJac1FjhTQQUN+ht5IJSXXVyvcA6HUdAI4jxgZ+xPwom8Wlyk5I8apLJ158KYysraXKQa1nY+Ii4b
tnwQiGx+5sjOWe4l2im7XZOSEnGyJinz54Az9kZnOexwruXVfAib99UxPwzlUqwqt8V0zyFIq+hV2tTg
vZPc4vmhsMUPKN8PNrvUtaT9FiXzC9IK4g0W3SRt/2bZpEdp1ju+b/sErB1W8gAxYxM+70TSqPcRC2tb
qR/3yHeukr4VIiVuny+OJKV/a7XeL+PwY9lgqBpATb3QZH3MXU7p3yaqGPzKbvbg47uiQ9+Gj0pOYvnw
+//ojo5s/lwTLrXx94IvcFo3CU50rdKCgoR6Ix5KqBGBUZhc8eMoCTg41qT9GWsYXhLZ8ep40Ga74yAl
4NRJbRtneIwKH66CSbRM5Y6XcgwPI+5Ss7l+tVkkHaim0DLNlCH+H758jYcAI2jrf6yhug/YkGOoMNEW
4CIDjG3jaZlOozAwrUHIG5iOmjmkWSMWcJ6nG4b+D9Y+kbJ5ZToqWeC0cE8uOa2xxOuSxDFBmmrKNjG1
f9E80uZtlC3mEaDwFNQsjkZztVDtrpyj/S7sOnoTNwyTc09WrGVmPsBAXxnoSTF4l5MT5ZUZaOVNHHN8
4eY+s8k+E5duBh4I3x7aG1C8kZAmy2fEFX9K0zFROOqZNq8wjTuDaQn9R6q3qeEK3Ml2KeL5W5snoEmK
dJACyT4NKru9gPgSOI5hoQD6IOtY6kXJwU2iem3y86dFUUQW/h0ache7PGhQmQLobBsfy8WErX1HRl/9
LwysV17T0vYLnKXWbtxnfvgaHr6Fh5/Cw8/+wVHR/hK+/T/3UJP2/3Esixm7bO18rLvBZml2A/PFdiZL
wDEpnj1Gi6IJ8GhFctnL4nUxpfnYlXTM9m+P1/o7ub8LQs5c+VVpjz8kU9vfYayU7wxARxc/64pMQzFa
hWL0ugglKako0rnHZU00lrQnDNcjRZKPORatJOVbMtwwPLxsKwB5wzkACsOsceuS7PeYEM79odM7AGMq
AwH7o8L4F1D7k3YIcn/ELiVgf8DuDrRbSrO3rymV5SvaA6A8H8tXz5iykvlHxAWUu74CYd2dfzmGy/Cv
WClj1hQbLhvWFAfcD9BtKVtrhzJhOZiUZRmYvFgzgFuqitVSii0HmJJWLHb2YTL2uvObIWxWOz8aOgTb
GmkWrOD7SilLSuJuanMMt2XfXlaVUvmfAAAA//87to5L/DoAAA==
`,
	},

	"/logic/labrynna.yaml": {
		name:    "labrynna.yaml",
		local:   "logic/labrynna.yaml",
		size:    9732,
		modtime: 1563912660,
		compressed: `
H4sIAAAAAAAC/6xaO4/jOBLO+SsKcNCJ0HMzsy90fummFxgKaKlscU2RAkm1T3fo/34oPiSSkntmgZtg
IFNkveurYqlP4AZhgUsJ3Np5RAtu4A4WPYN13DgQCtyAcNUGrQN9BSdGBK76sJHe0Qo7waSN49KCDids
ZxCVBYX/duC0Xxv5fQZnEIEbBC4ffLHAOyfe8ZUxz/ANzi2cYOIGlSO2oHSPFgzybuAXiXBZoMcrn6Vj
Azf9G/xXGzr1wdipkjOQFOoG3YCWaPuFlim+mPnFwqBni9syO4FclOLwBaye3QB20AbhC0xc8g5ZeNkJ
tySuF4P8DpfZDg1c5eywAewGjbb9iLvfhZT8hunARiLbeZG8u4PTDzTw0OaO2854vGWr7RIlg7abEbwq
TbW9IcnfUTZwF1KC0mbksm0/WFAr7A3ECoksYg/C4dgwAADPxz606RuYZtUNoC9/Yeca6MUonBEvNml9
Jl80sNmjbdvMXskBQXQcL2g8M9tANxvyNdkhmHsyaFGtmyMDI7r78mLhJvU72qYyPXI3oGmD2IVKF8M7
lOjaBs6JVRM0i6fIc2Ka0NgGDL+6NpHhN2KUqdSUpEc0Ixc92Fm4zbhBiV74WC40imyTa7xibcsuXEqt
FdzmJRcqN/5F6xENV7c2c8ymTW2b9DuYzp/wCh1Jw9US3G4HrR2abbs/Etzqd05443a2YLnrBlLgoseL
bXPp6F+uD8kkrmSIbLFlnp9bJorlTZ8iKmxH+R9/rJzDzxuXmJ7HxTo0QQWfSgXzeboZ3mPJv4FOzxRf
5+8x4kmUtmXk/LddJnUDvnMJRk/YgLCSsK8bPF7YQU8NfP8HmHlCtFUyhcW06+uvP9jGxwvlU4CaMjlX
WZ4lZJulbk0pQd8RKW98H+Ys8/bq4OdOSCmyJQdYfsU6J1qWoxRF2160yocN2Idw3QCD1vdnMIQKx6Ul
UFy0gUmiysBcanXzpyNoEtmka/8VLtraBvpv6eF7evglPfyaHn5LD7+nhz/8g68Ui5YSboa/48JNz8qf
ZTi3LAQRpQPteINzuT26w4N1rr5PMfhrHif43mZUXHBpSXXDumf4lpMQ6h2VE1od0Fn3M78As+rRpJAs
JW+ZXcw8HWi0PsId1zDPHLqB7qbkt4PKsrkziuNpThp/zHPFftZ/BVTOcNX98Jh37gMpJBU8tO4tO4Fw
FLXaWkEtiNO5l3xrozunjX82er4Nfu2iZ+kNp4k5GupPuDAC7UsgDGfkVqABcfUt10DGzpKOsHV2gbnS
vhmT+iY6anPYKbRZfERqjqxvu7iDbu46DZ0UEwirXvwh69/bcPiVlUJsrUwKnp0LMoTIkWsNk/iuKq+D
cCDxnQKwLEgwam2H9LOl0lnZpegWzj3e59jZZe1CZFqerCP/M8YF0ngpMkZ7q5ARyj3Qkb+Q+1zM1tv9
pgfWm7JszXIiyV2AQFEYQ1MSSmDA6bbkF9O0YPUzdaN5UokDw0KgnHvWXoTq8aSBoVahrUTVD/kG5wr+
a13KI1bLXvj+uFCwbANY/y1P970pvDhZLPmc76hWUe6FIh8TLCFB7JriNQcM2kmr3lJyJzKglVwaSjht
Yt5PBglm2Qmsvjqpu7t9ZSujiW+BRs3HZ/1lyrH1bJTnUWZF+8GcvvMFOrNYErQL9abgWTWioYjHA+3W
TUdKHp6PyWzZERzMHkL2EI7d+Hh0Ilh+Q+YTdFzBDcNd8sHNBJMWytE9zz7EONL1LRSgykEBHAn0CJsN
OrewE8xKKDeLcKesTqTcqGTaEFcKdfv86lNkTOygb/E+kqfzlkv+krdekIrUqbslqs9H/k0xsr91/Xy4
bG7fYHqNgHgTDSD4Pc+dQ3laNoi+RxU9HWPjqSzs0H2fngiEJ+2eBF7W47ETqHlWdGdfxhGdWcKN8ws4
LmcLE/K7Zb4Q+I3ZwCDas172VaJYDPOBDxbWCrlrk9b1KGJpuFyRh72wg7gNZASb9KPVvCmvXR3cuWmR
Cl2Igy3948ZNheON1f05dZgk32rF9R6eC7cRSNfX0uoxw7Icqen9aLSwj/L+lzUiSwFD5d0xqNKyuqGs
sV5JfjGaUK8gyG2IxTtSE9HpcdJWxKa52JX3zFnYHVe4ij7VJW04kYUHlzIFXVSg4rM5YAPfrb//YBNh
SxgPFVSLeszqu70dBMp80FBV/OImGFDDB0uua9G01ewp237JgWXvNTcrSkXXgNfBZ7bRkjAZjOhv+AoP
6nA5KHEb3MgNsps2WgFSmx3LOlylfuxaqLK78q1cyzxRD2hFJfbGyQivubftPg605I4cTfenCjbh9Uze
K/PjXIj/bHAVFNm135VilRwRcfaStawwd3gXE/rn6mHNOCL/qC9SKLgjTm/HhtxfVVmPtAg3Q/8HCk8O
7wdTa3dRKnSUjRsaHTBsEsPSQ2uHtAZR8f7Aw6PoK/+G9Qu39UAuYHGza6c7rgj+4vFDYVexPlj/a1nF
9UPFe/he3qRELsyax0fqP9OpCtOcKrfO35TS4W3VNxQkcuoAJN5Q9dFZe8la1v+2diOZjlr2axORaVoe
nbSW1KD3v+VHj3xR9iMBDnran9XFIw7ZzgYewg0g0Tk8sEcTQSa8T07wVq3R6HxktPL+WoRV5S8PE8WG
3HcHr2ufxdpIzYykPM8CbUfvSPCk1P76fmT6mlvEngwP137lgzlu6PLQcePs255fcWwna1sch69vcM4X
qtffdq+DA29cSgKULKLybT8sE5GM7xEJrCK9Nzgf0yettOlrdCNX/S243qDvCZ/tav951Bx6uhxRlBiT
Iuug5B4LsW+5yxp4fPupRVrPlBEWtz+x5ieB+lniPLZpwzbpjJi+tdsf7Ojc89z/ex3upzl9LFo2i10J
lGZsP+AEEmmJ9z322ZhjG3LUar09M1CcGxCke9G2FHqK5evho1lyNMr6QfBYryheL/johzifipijLPN0
QqQOyPttlvT/Beu2ZRdxgwv3cOAHKZ4p7/EQxsLSn/8M08a6QpWIZ3iPYHR3h4sR9o7+81wFufnr40oa
yARLvHP/4aUmsr3cOxDD1coTkfydw1+z8G7ffjR14AWcfLEwiJ4SdZK8wyc9YYyrjG36DnbU98aiHcKh
bJALzHteiRInysL9eb6LI3aC/2izfo+DL+GnRW5f/RwReNdh/N7g2wg3KwR9TfNYDUqzE/TCOqE6umdZ
uKB7IKpgYa5Wwf2fWygketwsryznnGUaQefBvLct9qcKk6/9jT8c2N/uO4k8fKKgqC9YbXGcL8dN1efN
gx1//iu5ohQ2Zuzk/97CfzNvtw8QnSbjHVM9UetIeBK+pDRw5Wb0f2Jhvbmp5HOYtL/16usVRj5JZHcK
VqK0kyTYaTHz1Hi6bcukuBheTF/KI+m9/1K1bub2053r2FvfKYQscml3HxdXP+wokXEWsldPfeoaqKuV
Mhey/vccxFfVCz+zq7ADmhe7fk8PbjoKxGzSR3ReLBh8hC+s8bOsTyaL3GvmtBktfEm/lQaDbjaKTcJw
J7iCjk+OC/XJ+LGJudhxiS0rKUdL/9zR/o/jUaqHgzDixAUvfjqT/aFOmshPeh2YZ3/1wRXGYKlZr3P7
Wnmy1R9Z+1hE/v8CAAD//2lqcgUEJgAA
`,
	},

	"/logic/portals.yaml": {
		name:    "portals.yaml",
		local:   "logic/portals.yaml",
		size:    2755,
		modtime: 1563912858,
		compressed: `
H4sIAAAAAAAC/4xWzY7jNgy+5ykIzKEXY4Fu220xvfYtAh9km7HVSKJBUUm3Rd+9sCU5/pFnOpdBKPLj
30fSbyAE6AQZFIzEogxYVM5P8qcyd9BOCLT8Piv+pWX3TEG+XN7mFw+KEZhIwFGHHrx2LWbUlpzDVjQ5
D61y0CCwch1Z/Td2E8SoNMOPl0uMBpUXZAc+NIEbn1De4ZoEFRC/w7VhVHdogh8quJkgWNeXOcoz+39m
s/rf7OdBplWO0M8WLzeCdjSYwE6UXlgp+q8Z1Y9EBvxT2XEVOQUZorCChlWLBiXlcQGAmEC1Me7wpoIR
8MFa5PKbChKsq2aIa1KQMDmZobNpVKvrpBjfCnBPPaVQ7aCitK4r8AM90HwK40fWrt/DROkEEzt3M/Sc
YFOhS3Xbd8yHhslrBVbxHVcta1C1QwY6UTq07KcMa+ULtKFt6QVoKTiJwgR7VDpEJ6xcj9AwyYC8Iu4N
1SSpYNAdgnIdeMR7jvfM7BDwz8uEfMfeKO/BqDu+3DhiGWAgJrehQWzXE2VrmF6X4Fi39+8/+MxFS+SH
/DP1fPqLRkaPI7Kv4Nppq4X1yzDzu94Sbh3dnnCJYjsnfwY7wrdqFeLOV10v9CmXZN+inlEJ3AI71a4K
lwQJqqx06MYvGTSm9NDGqH4FuhHHzGYIq3rdQkNkcWp8BddBcVdBzHZJqIy6T2ig4BHoBqNmJbjiXBRE
hYl4AgYfyAv6id0hzW/ZVVyLwGiVdh7m6d0vzd3rkYQN2WaHVEFq74YtO7wzwqywZ9s5uZ1tmJiaIn0x
bOnHJ55ycCtypobFbZjXWTxEqYkH3Y885XWZFuQ2xPWuLLkqzM7/cZlvyvy/6PIzJx/Bp7OU7845/DLY
+cYs9P+QbeeX/ImFIw1v4GgSe68bg/DUMlCQ+ctFux5umr3sz30RaZmKX0+mYs21TMyPRqM0D5fPqFns
3nZjzrjzr68VWNU7FOgNPdCfVXgb+b7Cf/w2fSqycuu12b2ECbOktq6d7u7wHJBx+ogcg4AM2l8KRXhP
o1zsRyybry//BQAA///0uJ1dwwoAAA==
`,
	},

	"/logic/rings.yaml": {
		name:    "rings.yaml",
		local:   "logic/rings.yaml",
		size:    1502,
		modtime: 1563912611,
		compressed: `
H4sIAAAAAAAC/3xUPZfUMAzs+RXpqI53d3TXQUPDP+BRKI5ii3UsI9kXFh7/nZfQZCPtNSlmotHoy7MQ
lkkT1UGoxJfhD8vL8O3733eVV5QdHL4+PN0jnu8RHw8EyMKu1A3xfI84SglOZ6Nj7njGoiCWMxi6qA3H
XxWlvVcrC9rOoECJXiFfPn8aGi3GxwI1o9XWhjDNjn7FCNrN/43VYAlBmuflhjg2VVdaFhRrJySQaLxn
islNcEMcE4y8jJ7+/2nkHi7u7Dwicp5cYlsAN2DPkThf3RwesUl5uBZeNbFpiHCwtf3sFC4KZfLUf7Dv
xsH3gj18r8shJtLAryjXt3b0OB0Ojc1+8pip2Mlf8GH7mM70UVgJTMRMom2I9ua0WvltTaowz+YUC0q0
hY75w4BTtKe7XV2B1sUazXD1NlF6RfPzK4XGto9K0Vh/enxs6QyuidQ8nxE0gT1vCCb9bxaw/bRvw5po
UQqQjapww9CIjd1/AQAA//+3cBgt3gUAAA==
`,
	},

	"/logic/seasons_dungeons.yaml": {
		name:    "seasons_dungeons.yaml",
		local:   "logic/seasons_dungeons.yaml",
		size:    10632,
		modtime: 1563912777,
		compressed: `
H4sIAAAAAAAC/7xaSW8juRW+1694gA6zQO60V2kaQYAMkEGAAHNpBHMw6kBVPakYs0gNSVkjB/Pfg8el
uFTJYyRATt12vX35+PjoFfQneUAlDZhBnUQPGsUFlAT1ivqstOiBy73SI7NcSWAGBLdWIP3vqIzhO4Gf
mhXwHpkQF0BpUcOfg9S/ADdgBwQlSWoSaXF0vw90IFWPplmBxj1qlB3CM5M92IFZ9y1aJ5WFHUKPey6x
hwE1tp+aVbOC3ckMN0BMR2Vv7KDVmcsD6ecSBqZ7EOrAuzXsThbO3A7AJDC941YzfQHBR25B7ZsV2EEj
guk0ogSrmTScfDdwRA0d0/qydnqkglFpJCMl2LMClDhyNNAxCTt03vx64hp7sIqsfuFCYO+VK0mMWp0/
Nc0K+s+ND1z/+Qs8958pjJrJDltYOZ81k70a+Rv2RP4ZXvBimt79C92Axn6B5yihpQ/6dESMn/6t9Bd4
3mlkLy5OYNge17AXJ4vt7yTxliQRnzkr3c9EroE+jUwIomudybcx6FdjDXulgcEez6CVGo2PPaX9oDS/
MBcEqoxmBSOzFrUBvoeLOsVQEa2xTOyV8WHTqv801/q9VPZ70u3UNiunmHhfmeRCMPjxH86CNRhOtUUa
JPq8aBT8MHizrNLkOeAr6gtYPlISiVgge8VPMUe3MaI+djEbt5OpvVbHFL3bNThq8imSrGGnWYcCbdsS
514o6jFDDGTpnBvHHWowiL1ZwzMFeQ3jhRgu/retl7RTxlANzWWuIXwme9cuxMA0lXDfZjWQ3Kiq4NYJ
mKogSAjETndIa+SrRa0bAPiwN0G+JB8EfHvk9junRFB2YpBqFT4EQnUvN8eTGag+rlDmSfE6JkNSapw4
zbg4s8t1t7ykgVtv2zU5u5O1SuZiCskuB3dTLe2YwRHlEuUadmrcmTV06uQI7srMtAvJ7e9i9d4tV++d
r/4QLk8ROdbQ34FWxwAo7e9ELnBvYa/VOIEVmZqLaZvIFhqi+Frk15EyrdW5MIB+KeykwPgKquV8uD+8
4cmRoGFSOzfJw2gsoZLWJcFR7QTrK7C9bnku4iMlGI0Wgo6fZDaphzMTYiqHiYkYzJFrJnKGXERRbI5Y
StRzurLG7rIaa5te9UoeFKiz+ALPRaw9rRfqIxRQafqto4hg5Ky5n6yhENDBvxz2aND93KA7Ovtzl3NJ
FB86AI/KB2hUO8HldWqXG5+1Kichly5vkcfhU6ifIPnbAzt+13q7LGrizrVNgbjuULMCJjgz7jzD3yxq
yUSakZq8CkJRpEr0cQ82Z7HM/fbQcB+h4X4RGsyRv2APO0Qr0CynOwpom/4eOvdTwo/7DPj9mZFLXMPz
XvBj/csCPO9h5CPvCHe5NlOP3cOZpdPteVKdc/9O3HX3lPKKzsllZopK+lzVHpkdUAdNv55492Lc7OpT
vsQeWRo1nhi/0kBXmeiLEr3S43WHSvzv712d0OxJxZVz5YImSLOajUclOI1nV2yrvScdGVumYonyTYl3
STJwip5l5HnSC/DMseq+hIZ78LGOFXQ1KUGko/Z1+67UA2fShraLPVbqCuE3Zv7JCSxAsH+IvfiwfEw/
kLN0f9jnx27kCahF/XREkt+xI5KhDw4Zj6e3N+EqckHM0jHyACN7y7K5yDYNPn4aGLnEjmnP3jP9MsUl
l1YmO4yeDzG12dz2vmuT0f1DNpkmuIm+VIXyrBUBulIjaiYPrQ9RQInoQKE86Z3qJFcZQqyE97OSdDVG
NTBG+7LLQWqFg0YXnZ4bS5G/0ptz7bMqfiir+GGaZ1N3LPhwTcIM3ZeuOA85HtYK3fc9p8MtC/6MLMLa
4ST5yLxQNwZm9VlzhLFQcHkwg/IH3uPUS51mHR067qqU1WlpS3L9cSl4PX9FMEdll3kp9e4+uWc6XhDe
lRcn/yIbS1I/JPCghpFdLZVKVxvQxzF5xRWF54qXyNmFLsZ5PoJPGVjDv07jEcJQkM1XU2PN5/nZIN8E
K6YedRaHAnH//+PpyTOGavLOhhr1UPwYofhxGYofgVIBO3ZJSPE4gyk3oDmP78jswDRVbBLyHpA+Ovgu
ETGqeh7ZQaKFg1CvaCZAjPAaLx65Im9iDHcI/xEPzJwMGGa7AUXrw/wIB77r1Z+KEzuZU9+YHv21sNoc
RFMrS+Ph9Dgbj9/nK52Z/PDDS9s2NPcYeJH8MNgr82qt01lRXZkqI8zAUfTVaNU2q7iy6pj03+yAca4y
6/knZx2p82ZmQS0sms1wj/HGsFw8S4FyZffkQ0xXcNiFi8IHqq7UH/cvqwlgKfswIpMGtFugGd4jPJ8H
dCvR4AVw403PuD5ieSiNDKyp5oy9MZeDv6eWMheiFSTuiok3r9wcMx+Xz7PUxj6UU7N4+5yefFGThdkJ
TSavofSwOJNnFmSn6UgAhea0rmAyag+D5Xu6INAlyP4DxVNLkUafhv4pouHTMho+we1PgCzvnKeWfl2s
UOKXtD15KhJVbk6frkDchG0ThDjtacIoDOj0hUqFrifH2g5H8M+buXVuVRA4XTx5l82LxOVHj3RGRznT
zOHOKqJEQ2ZOtV+y5hejJ3jlOhu3C9Z635qtTJ5gh2xM7ZX8yHcLT+Wg8QR3P3lwzxVmgiJNhVM1X55K
TzoElKm5S1cjmrkbRWF0faAVucias6jSfGGT1jP1zXAWh2wKKQ/Oct4teNo4JlG2vKMpb38Q86PGG9eL
RaqIPeQ3+++0W/IB+c4JiA1fiXK6quX+yOTAZC/8LNRv3NtWBGar3A8eu9Xe/RDvdMANCNX5dczAZQ/B
B5M/suywYyeDxHxUCOaFH9MLD/1m72Rza1DsSaR7BCzlKpmeVTaLwEKCupM2+O7iadM2/QbO/O1Nq91s
jtjUY8pmcR+SqENFTzdT/4VM+WtB128Wb50fH4ZbZ8x8uNuk21OxicwMCT650HOSG0e9sK2sqnk+3pFm
Guv8uwTV1CY7HVOrbkIPp+1BTueMCxN92bleQzy/EoCU8qbrAFTHXSkrXwltsi1bJnVme9nCm3q1GtAz
hfTHWk5xB8nberM8LlQxXsNwOZaFEA5UqlV3l5+Oj8yKtGxwhG4vmvuZc2bK6aDI0KyI6jTFsU4TRrhh
LiOeAlYl0MXpYQp7uQyqLKnL0R/O5bzxMMtDv4Ef736aHog2xYpocfj35R1H27YxA5dcHmAnTtdWIpvZ
I+FmwtFSY/iQgehBIKqXYhTdJNSc7+A25WA587Z+XK0MuMb7bpWlKW3brODvX786MHaQe3Jm+ud41y9M
gkDmnr5f8HJDcGw+NSuqegO9kt9YGE7aZo1oByZf4KBUL9GYCa63y3PgFvCC1Ry3zd5eQlaZzGCwAK7F
NUB01XRuFRF/nBKd7qxkgf8LDrzg7A17m+SngJItdafWy4n/3pjqNSsZUuBdQRq7YVs9SV2ZCtICdRvQ
Io6atQAiSO/3CTaKrrpvi7WjFxqfB3MNJb5ui0o3XFBwzhSLK125zV4It8UtIJmfU1Rz6Da9oFVHRfqU
U2fsbbPXl6MSTF81raDut26RLU/2isDpuM3R9v9TYdk1YAu8w3CsZjEs7MxPse38TwZiXLx1xflX2e+i
clTCwKvi+cvmzIosDvEWXd2ncgh7mJyJ97bkSS24OFfK+nMamHAs13KcK3DuHAZlbIhX6sGcLF12tvDz
3+KnRbppfJsWLI7r64e4IqlgrywPbeIOZc70y/J35+HP2Y/56/cWvv4yk12Go1nB05SKn3/5mKsxH0+z
fHiV/6OQZgWbyaZ4gOeCvdO/lJfFKG8zK/kgJb8yYX8yDAZk/s9mlFS/fWOgY8aKuDHufyC1P7z3N3q9
ktlI8EOFCwVYkIa2+U8AAAD//xHMEVqIKQAA
`,
	},

	"/logic/seasons_items.yaml": {
		name:    "seasons_items.yaml",
		local:   "logic/seasons_items.yaml",
		size:    3253,
		modtime: 1563912777,
		compressed: `
H4sIAAAAAAAC/4xXP4/buBPt9Ske1sU2RJBf8svdYevr01xnqKCkscWY5AgkZcc47Hc/UH8oUvYiqbyk
5s08vhkOZw+gn8FJWO4IlgPOZMnJQB2aO9qe2ouyZ1ylVVpLtGwD2eDBJ6hABl5z8NWJWb96sKM3/Mvu
Dcf6vaocd+vypmwgJ+BHY6bfwSl7FpBjGI2djFV7ub96nPQYci+dMio49eSLYfb9k/3qgH++//39DaFX
HspDohtNg0HLlnrWHTmc2GG0QWlYuuGktI6Ghh2hoytpHqir3DgQ+dXzy7wU+Pr5RSCtvhWr/32OSzIN
OXiizosKAI69dJ2A7/lKup450s+BXHj1iEqglRYdw7OhyNuePUIvA07Kh2TxGgQ8p3PFQ4SeqgM038gH
tGwMW3Rk2SgrA7tP1TDatgc3P6gN61GSU1GyqN8Xc7Jk7qv1Qj6B6kdUdcDg+OzIe3UlX1luNMHf2MUK
aHm04Q3HL2LeirmTZ9WiYTbkpD2XRmm7fq/6+xCl1FGRnsPO27pdv1etHKj8eiIZenIzvUkzPqHl0XlC
x+Tta4AcBn1HYEitEdyUw2YM85+4cbTp5ZUg7X1OaHWADEG2PXURF3oyGK0mHxNG9ymRDaGX7ko+UPcp
ZkwF3NhdPHgMnypHU8FN7laRF/spsMCu6NOGWCupcSQvaEbfT9W0orPCe8Mx/k63VGCKMZfibBPjLBWK
nE+dQnTfIJ1hH5uAD3VRyGu8SGBxTvGCQ55Hq4wUmJfdn3Vd14meuftA7v4LgqvVxxRzKt1fOc2SWh7b
t2TDFnla5REyLkWw5GCgs/Sj/wX51er3yDck2z72BUW6i34IbT/ai6/rGgcY6S4UEoOz1JTCT4vfOkC1
VIUMbU86q7W8Ta2f6yol6cG+SF+GWKR9sM8kz6yTjg/2hcIZYj73g/kmR2Y73dPVdL5axfEFducTKOjP
6dlxFMgpxAu3+Nza0geipga1yfoEsxd2Qy3cnmBKcTdEov4Esxd4Q83newIpRN7sJ5mzppwLvW5nUqet
Sd3doQQeOK+CZ/09Rnx4DI67HYGC2Fb7y6V5nqT14mRJ2tnvE7QhyrbyPDmb9b6HfJSYDVHc+adJ2Wyr
hk2DUxwGpld+dFa2lB7C+GrIljRFXYqhqZi9BIrB6uExiuU/N6w03DF3ZFMXU463xXFpcZni8cVKrFcf
223Mch7Pk17Ioul/QaNlR2vTTwcTOKCjywjfurERyyA4T2cfP2DR3eIBjtmsTfplIhCnupelyc8T3Pr+
zlKLRZdlrvsxmgE/MaiAoDT5atr4mqaplI1dk6kF4gyzHHt282VFzT7S27xlNBKsC0yKFL0lxOrgCeD/
RZA/EmTGJ8D8Nfnds9+GkPgopbTGeU/AcSSd/kkQyKfSOOVl6dhBlxRs4Pq9+i8AAP//9RbD3LUMAAA=
`,
	},

	"/logic/seasons_kill.yaml": {
		name:    "seasons_kill.yaml",
		local:   "logic/seasons_kill.yaml",
		size:    3574,
		modtime: 1563912777,
		compressed: `
H4sIAAAAAAAC/5RWT46jPhPdc4qSsugZCfUBZvMdJGJRmAI8bbuQyySDRn33T8ZADCQ9/dslxq4/r957
9gVCT0LguCGBhsFxgIZa7Qh0ICslsDMT3Hut+rQCCh18aGOWRXJkNUlxgdE15OHeYwClvRqtBHSKpAQU
Ga12HYT4ceLx7UaA3usbNaBdLAI8swXFLqB22nXFXNocfXovLsUF0E2h34LEKmqChiR4nlIYy57iVwfs
CO44gRZAIwzaKTM2aVdPnt6LC9Sj9LG41vCdvJRgR+ljFVICBbUm1RYNKLYDOs1OAD3NKOUhQ68FDHda
lSDaqVgFTW+eZvRimBtqg7WhuFuRj03GSCjvRSEYVE8mgerYWzS/4LqslgUAAPtfcCVbkwchaqSEa4++
KdMHUeTC+qFDQ+l3VVVVIUa7TnoOx/Dr+qsEL4MWv0c7HKK1hKEnX+bLy8ZBhyf74upub3FZmQS30Tjy
M1qB8zpm7NHccTpturNvAF0DLbN5i2yMXPgRV4bRqZ7kfz/fizkj+siT5hf8TeDFo+VyLp4q04lEvYTO
HuF0bMNvHcUysIj6Z7HQV7AluJEXzS6SsWWfxg73SMMohcjktwADi+jaTNBRAAmj+oDWs4Wakhg4qeTu
2XUguiHgFnAm8XtRe8KP+fec8dCaxU4rqJkteXRdCbVHRYZCCfnE507ToB+91WxrqT6zDN8NHkHYkWR3
7AnnS3jK1VTXi/FUn8WBScc8vSbTlOB5P+M5aE6H6jNVKwFNy7KG2dXnOW7rdQBDN/JpQFY7UujDIXGG
yJw7Z9Cc3E4SyE8rqdBNOe7nfrn+TSrk+beMPd/IlPCisLWz1AX8GHT4+bS9oyZTqhY9yF0HtU0+H3ak
x6n4FQNy5LsJvHZdtVYRtRL9e1fGGbMv53b9lwL/6YtLMZZrox386HA41rI7+5yYp7qOxljCwQH3tp3b
TK7Eub4kuIE3XjmOXrci9RBZa/QAMugPaqAmCuYh/wXDxI/qs7js98liPTUtHtnM/iRsCaJHsUvBky72
Ga7ntNlF8sRTvy/4qiqeZfz7CP+iqvLkXgva+eiXybMdUa8CWCwgg3WBPz0Nvna8NSJ2Y3wrHK/RncfM
grpF1UdV7UR88tGdpjIt7k692r/oJLW/Xbp5FwdhPTTRcR+7+HtWUE7RlaDrm+llGxlTF8mZhr3dGdDB
gpe/T5xqG1Si9laF8lP07ZOdzOaU3XZ/BvLhTZIjHQ3JYudoTvhgWlqDzvCN5B/8Ws1niXvTnr54Yxxr
abXT0oNF16NrDB6OfnE9PO0qi3OeyTHXIriBCUTHW+k56DNl9iRYcnWjIxn/Q7f7OaPyLAK7GyER79Hx
fhKJ3goH2isscab6+grqDBF/fO/9t55p/TSwwQ2Z68aqjCzrjX4iyPZleyKeX92nQ8v6dmRFm5pREHrC
10/YzeUc/8m+Jx+oiv8HAAD//8X7uFD2DQAA
`,
	},

	"/logic/subrosia.yaml": {
		name:    "subrosia.yaml",
		local:   "logic/subrosia.yaml",
		size:    2392,
		modtime: 1563912858,
		compressed: `
H4sIAAAAAAAC/4xWTY+kNhC98yue1Er2glra2V0p4pxD7jmOOBRQDc4YG7kMnVG0/z2yAbdhepScBrm+
33tV0xfI3DgrijCQQHhhRxqaXM8gxyS4D6odwjf6mRwZz9zBWzQM72hhJ0yNZpAUF2hrepDg3c5oyaBn
Dz+wYygTPnBTTjwmTS1XxaW44OsVnsdJcwVnhTBZ50mX6Mi0jIG0LjeHEjIqP7wXF7xc0TC1QwW50zil
oJHcG/tyNRYXfLtiUB2DTAdhfqvwx69/lhjtbDwpk+Jkcsr08PbOrrjg+xWTcuQZg52FKyxKa+o5+a/W
MPCPKxqnup6r7W9EDa8rgs3sYazHokR57gIIZN5/qePkt9kZahmzJEBtAEkJtJIwxeyfADlLaJVCJjWS
Li5o7TiRUSHY4q95nGAXdhHuwWoWkAe/c69JBJreApI2Zr5b88XDcMsi5JQO2A60MG5Modq1KHZy/rGu
wmsBAPy38lisbslYFjAFRldkov01wl/Cqaaxpj4+bpn31wM9JRo7NusI31NchPURWP8sio38c09Jy6sO
jk2dKm3pSjSOWtZBNTHbo4OXoKfesEev7cJS7x1txOWhp6mSR0zZ0sQlXgdyXT7ht/pjxtTVsfLmtu9B
DsVJ368pwxkb78gESTob7HLS8qr0HfIHC1uevfJKRl3XdVEcV2TlIpaKL7C3fU1SqU84iHNsEHwktXdM
Pi3LM539T5A37wOyJ1ltm5y18AHzLdlpB+782IFMFnkf/y340MIuYZMdwIR/vW1jwFaYxBrJbEn9waQ6
rtLIMtiFdb0x9kXQcJa1hJvFv8fHuog3MBS4K+M55z6CMiiPGznIXfl8nbNAmccxBh7OwAOW3DXe3epT
YTw8afbzaKoPfGwI3nRwrDP47kp3gnZg8R/zZ4o5rfgDxf3mbylyTTxT0uer/Hmx+mcqV8JObNDSEnlb
1yyzatu+cZfsR2QTXNaFfmfzJnvDK/Wht2011te7jWuShDpSr1o01o4czkSJZzo8NJz+134VD+V5zOTm
ycG6XJK784vpTs6Plkvw2LALFHXyJPaHHz6NrYvDmagyHhx3wbFEo2dev9I1ey6d9WdGprWA3DpQ0f0G
NuGUxiLxCvz+eNpOQF38GwAA//+vBDRzWAkAAA==
`,
	},

	"/hints": {
		name:  "hints",
		local: `hints/`,
		isDir: true,
	},

	"/logic": {
		name:  "logic",
		local: `logic/`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"hints/": {
		_escData["/hints/ages_areas.yaml"],
		_escData["/hints/ages_items.yaml"],
		_escData["/hints/common_items.yaml"],
		_escData["/hints/seasons_areas.yaml"],
		_escData["/hints/seasons_items.yaml"],
	},

	"logic/": {
		_escData["/logic/README.md"],
		_escData["/logic/ages_dungeons.yaml"],
		_escData["/logic/ages_items.yaml"],
		_escData["/logic/ages_kill.yaml"],
		_escData["/logic/holodrum.yaml"],
		_escData["/logic/labrynna.yaml"],
		_escData["/logic/portals.yaml"],
		_escData["/logic/rings.yaml"],
		_escData["/logic/seasons_dungeons.yaml"],
		_escData["/logic/seasons_items.yaml"],
		_escData["/logic/seasons_kill.yaml"],
		_escData["/logic/subrosia.yaml"],
	},
}
