package main

var generatedPoints = map[string]Point{
	"beach":                Or{"beach 1", "beach 2", "beach 3", "beach 4", "beach 5", "beach 6", "beach 7"},
	"bridge":               Or{"bridge 1", "bridge 2", "bridge 3"},
	"d2 arrow room":        Or{"d2 arrow room 1", "d2 arrow room 2"},
	"d2 blade key chest":   Or{"d2 blade key chest 1", "d2 blade key chest 2"},
	"d2 compass chest":     Or{"d2 compass chest 1", "d2 compass chest 2"},
	"d3 basement A in":     Or{"d3 basement A in 1", "d3 basement A in 2"},
	"d3 basement A out":    Or{"d3 basement A out 1", "d3 basement A out 2"},
	"d3 basement B in":     Or{"d3 basement B in 1", "d3 basement B in 2"},
	"d3 basement B out":    Or{"d3 basement B out 1", "d3 basement B out 2"},
	"d3 feather stairs":    Or{"d3 feather stairs 1", "d3 feather stairs 2", "d3 feather stairs 3"},
	"d3 mimic stairs":      Or{"d3 mimic stairs 1", "d3 mimic stairs 2"},
	"d3 trampoline stairs": Or{"d3 trampoline stairs 1", "d3 trampoline stairs 2"},
	"d5 large rupee chest": Or{"d5 large rupee chest 1", "d5 large rupee chest 2"},
	"d5 stairs A out":      Or{"d5 stairs A out 1", "d5 stairs A out 2"},
	"d5 stairs B out":      Or{"d5 stairs B out 1", "d5 stairs B out 2"},
	"d6 map chest":         Or{"d6 map chest 1", "d6 map chest 2"},
	"d8 portal":            Or{"d8 portal 1", "d8 portal 2"},
	"dragon key cross":     Or{"dragon key cross 1", "dragon key cross 2"},
	"furnace":              Or{"furnace 1", "furnace 2", "furnace 3"},
	"ghastly stump":        Or{"ghastly stump 1", "ghastly stump 2", "ghastly stump 3", "ghastly stump 4", "ghastly stump 5"},
	"goron mountain":       Or{"goron mountain 1", "goron mountain 2", "goron mountain 3", "goron mountain 4"},
	"hide and seek":        Or{"hide and seek 1", "hide and seek 2", "hide and seek 3", "hide and seek 4"},
	"horon village":        Or{"horon village 1", "horon village 2", "horon village 3", "horon village 4", "horon village 5", "horon village 6"},
	"lake portal":          Or{"lake portal 1", "lake portal 2", "lake portal 3"},
	"mount cucco":          Or{"mount cucco 1", "mount cucco 2", "mount cucco 3"},
	"mountain portal":      Or{"mountain portal 1", "mountain portal 2"},
	"mystery tree":         Or{"mystery tree 1", "mystery tree 2", "mystery tree 3", "mystery tree 4"},
	"natzu":                Or{"natzu 1", "natzu 2", "natzu 3"},
	"open floodgate":       Or{"open floodgate 1", "open floodgate 2", "open floodgate 3"},
	"pegasus tree":         Or{"pegasus tree 1", "pegasus tree 2", "pegasus tree 3"},
	"pirate house":         Or{"pirate house 1", "pirate house 2", "pirate house 3"},
	"post-d2 stump":        Or{"post-d2 stump 1", "post-d2 stump 2", "post-d2 stump 3", "post-d2 stump 4"},
	"remains portal":       Or{"remains portal 1", "remains portal 2", "remains portal 3", "remains portal 4"},
	"ricky pen":            Or{"ricky pen 1", "ricky pen 2", "ricky pen 3"},
	"scent tree":           Or{"scent tree 1", "scent tree 2", "scent tree 3"},
	"sokra stump":          Or{"sokra stump 1", "sokra stump 2", "sokra stump 3", "sokra stump 4"},
	"spool swamp":          Or{"spool swamp 1", "spool swamp 2", "spool swamp 3"},
	"square jewel":         Or{"square jewel 1", "square jewel 2", "square jewel 3"},
	"sunken city":          Or{"sunken city 1", "sunken city 2"},
	"swamp portal":         Or{"swamp portal 1", "swamp portal 2", "swamp portal 3", "swamp portal 4"},
	"temple":               Or{"temple 1", "temple 2", "temple 3", "temple 4", "temple 5"},
	"temple remains":       Or{"temple remains 1", "temple remains 2", "temple remains 3"},
	"village portal":       Or{"village portal 1", "village portal 2", "village portal 3"},
}
