package main

// list key items and key slots here, to be used when the -keyonly flag is
// provided.

var keySlots = map[string]bool{
	"ember tree":             true,
	"d0 sword chest":         true,
	"maku tree gift":         true,
	"d1 satchel spot":        true,
	"dance hall prize":       true,
	"rod gift":               true,
	"winter tower":           true,
	"shovel gift":            true,
	"mystery tree":           true,
	"d2 bracelet chest":      true,
	"scent tree":             true,
	"blaino gift":            true,
	"pegasus tree":           true,
	"floodgate key spot":     true,
	"square jewel chest":     true,
	"star ore spot":          true,
	"summer tower":           true,
	"d3 feather chest":       true,
	"sunken gale tree":       true,
	"master's plaque chest":  true,
	"diver gift":             true,
	"spring tower":           true,
	"spring banana tree":     true,
	"dragon key spot":        true,
	"d4 slingshot chest":     true,
	"pyramid jewel spot":     true,
	"autumn tower":           true,
	"d5 magnet gloves chest": true,
	"round jewel gift":       true,
	"x-shaped jewel chest":   true,
	"noble sword spot":       true,
	"tarm gale tree":         true,
	"d6 boomerang chest":     true,
	"desert pit":             true,
	"d7 cape chest":          true,
	"d8 HSS chest":           true,
}

var keyItems = map[string]bool{
	"sword L-1":          true,
	"sword L-2":          true,
	"boomerang L-1":      true,
	"boomerang L-2":      true,
	"winter":             true,
	"summer":             true,
	"spring":             true,
	"autumn":             true,
	"magnet gloves":      true,
	"slingshot L-1":      true,
	"slingshot L-2":      true,
	"shovel":             true,
	"bracelet":           true,
	"feather L-1":        true,
	"feather L-2":        true,
	"satchel 1":          true,
	"fool's ore":         true,
	"flippers":           true,
	"gnarled key":        true,
	"floodgate key":      true,
	"dragon key":         true,
	"star ore":           true,
	"spring banana":      true,
	"ricky's gloves":     true,
	"rusty bell":         true,
	"round jewel":        true,
	"pyramid jewel":      true,
	"square jewel":       true,
	"x-shaped jewel":     true,
	"master's plaque":    true,
	"ember tree seeds":   true,
	"mystery tree seeds": true,
	"scent tree seeds":   true,
	"pegasus tree seeds": true,
	"gale tree seeds 1":  true,
	"gale tree seeds 2":  true,
}
