package hints

// rules:
// - each dungeon is its own area
// - single-map-tile non-dungeon locations are not their own areas
// - areas go by map tile names unless they're on a certain side of a
//   boundary tile; e.g. waterfall caves in sunken city are labeled "Mt. Cucco"
//   on the map, but "Sunken City" in this system
// - subrosia is partitioned into "North Subrosia", "South Subrosia", and "The
//   Temple of Seasons"
// - caves directly entered from rolling ridge base are "Rolling Ridge Base"
//   until they hit a stairway, at which point they become "Rolling Ridge"

var seasonsAreaMap = map[string]string{
	"eyeglass lake, across bridge": "Eyeglass Lake",
	"maku tree":                    "Horon Village",
	"horon village SW chest":       "Horon Village",
	"horon village SE chest":       "Horon Village",
	"holly's house":                "Woods of Winter",
	"chest on top of D2":           "Woods of Winter",
	"blaino prize":                 "North Horon",
	"floodgate keeper's house":     "Spool Swamp",
	"spool swamp cave":             "Spool Swamp",
	"moblin keep":                  "Moblin Keep",
	"master diver's challenge":     "Sunken City",
	"master diver's reward":        "Sunken City",
	"spring banana tree":           "Mt. Cucco",
	"goron mountain, across pits":  "Goron Mountain",
	"mt. cucco, platform cave":     "Mt. Cucco",
	"diving spot outside D4":       "Mt. Cucco",
	"black beast's chest":          "Western Coast",
	"old man in treehouse":         "Holodrum Plain",
	"lost woods":                   "Tarm Ruins",
	"samasa desert pit":            "Samasa Desert",
	"samasa desert chest":          "Samasa Desert",
	"western coast, beach chest":   "Western Coast",
	"western coast, in house":      "Western Coast",
	"cave south of mrs. ruul":      "Holodrum Plain",
	"cave north of D1":             "North Horon",
	"cave outside D2":              "Woods of Winter",
	"woods of winter, 1st cave":    "Woods of Winter",
	"sunken city, summer cave":     "Sunken City",
	"chest in master diver's cave": "Sunken City",
	"dry eyeglass lake, east cave": "Eyeglass Lake",
	"chest in goron mountain":      "Goron Mountain",
	"natzu region, across water":   "Natzu",
	"mt. cucco, talon's cave":      "Mt. Cucco",
	"tarm ruins, under tree":       "Tarm Ruins",
	"eastern suburbs, on cliff":    "Eastern Suburbs",
	"dry eyeglass lake, west cave": "Eyeglass Lake",
	"woods of winter, 2nd cave":    "Woods of Winter",
	"shop, 20 rupees":              "Horon Village",
	"shop, 30 rupees":              "Horon Village",
	"shop, 150 rupees":             "Horon Village",
	"member's shop 1":              "Horon Village",
	"member's shop 2":              "Horon Village",
	"member's shop 3":              "Horon Village",
	"tower of winter":              "The Temple of Seasons",
	"tower of summer":              "The Temple of Seasons",
	"tower of spring":              "The Temple of Seasons",
	"tower of autumn":              "The Temple of Seasons",
	"subrosian dance hall":         "North Subrosia",
	"temple of seasons":            "The Temple of Seasons",
	"subrosia seaside":             "South Subrosia",
	"subrosian wilds chest":        "South Subrosia",
	"subrosia village chest":       "South Subrosia",
	"subrosia, open cave":          "North Subrosia",
	"subrosia, locked cave":        "North Subrosia",
	"subrosia market, 1st item":    "South Subrosia",
	"subrosia market, 2nd item":    "South Subrosia",
	"subrosia market, 5th item":    "South Subrosia",
	"great furnace":                "South Subrosia",
	"subrosian smithy":             "North Subrosia",
	"d0 key chest":                 "Hero's Cave",
	"d0 sword chest":               "Hero's Cave",
	"d0 rupee chest":               "Hero's Cave",
	"d1 stalfos drop":              "Level 1",
	"d1 basement":                  "Level 1",
	"d1 block-pushing room":        "Level 1",
	"d1 railway chest":             "Level 1",
	"d1 floormaster room":          "Level 1",
	"d1 lever room":                "Level 1",
	"d1 stalfos chest":             "Level 1",
	"d1 button chest":              "Level 1",
	"d1 goriya chest":              "Level 1",
	"d1 boss":                      "Level 1",
	"d2 rope drop":                 "Level 2",
	"d2 moblin chest":              "Level 2",
	"d2 roller chest":              "Level 2",
	"d2 left from entrance":        "Level 2",
	"d2 pot chest":                 "Level 2",
	"d2 rope chest":                "Level 2",
	"d2 blade chest":               "Level 2",
	"d2 spiral chest":              "Level 2",
	"d2 terrace chest":             "Level 2",
	"d2 boss":                      "Level 2",
	"d3 roller chest":              "Level 3",
	"d3 mimic chest":               "Level 3",
	"d3 zol chest":                 "Level 3",
	"d3 water room":                "Level 3",
	"d3 quicksand terrace":         "Level 3",
	"d3 moldorm chest":             "Level 3",
	"d3 trampoline chest":          "Level 3",
	"d3 bombed wall chest":         "Level 3",
	"d3 giant blade room":          "Level 3",
	"d3 boss":                      "Level 3",
	"d4 pot puzzle":                "Level 4",
	"d4 cracked floor room":        "Level 4",
	"d4 north of entrance":         "Level 4",
	"d4 maze chest":                "Level 4",
	"d4 dark room":                 "Level 4",
	"d4 water ring room":           "Level 4",
	"d4 pool":                      "Level 4",
	"d4 terrace":                   "Level 4",
	"d4 torch chest":               "Level 4",
	"d4 dive spot":                 "Level 4",
	"d4 boss":                      "Level 4",
	"d5 cart chest":                "Level 5",
	"d5 left chest":                "Level 5",
	"d5 magnet ball chest":         "Level 5",
	"d5 terrace chest":             "Level 5",
	"d5 armos chest":               "Level 5",
	"d5 gibdo/zol chest":           "Level 5",
	"d5 spiral chest":              "Level 5",
	"d5 spinner chest":             "Level 5",
	"d5 stalfos room":              "Level 5",
	"d5 basement":                  "Level 5",
	"d5 boss":                      "Level 5",
	"d6 magnet ball drop":          "Level 6",
	"d6 spinner north":             "Level 6",
	"d6 armos hall":                "Level 6",
	"d6 crystal trap room":         "Level 6",
	"d6 1F east":                   "Level 6",
	"d6 2F gibdo chest":            "Level 6",
	"d6 2F armos chest":            "Level 6",
	"d6 beamos room":               "Level 6",
	"d6 1F terrace":                "Level 6",
	"d6 escape room":               "Level 6",
	"d6 vire chest":                "Level 6",
	"d6 boss":                      "Level 6",
	"d7 wizzrobe chest":            "Level 7",
	"d7 spike chest":               "Level 7",
	"d7 maze chest":                "Level 7",
	"d7 right of entrance":         "Level 7",
	"d7 bombed wall chest":         "Level 7",
	"d7 zol button":                "Level 7",
	"d7 armos puzzle":              "Level 7",
	"d7 magunesu chest":            "Level 7",
	"d7 quicksand chest":           "Level 7",
	"d7 B2F drop":                  "Level 7",
	"d7 stalfos chest":             "Level 7",
	"d7 boss":                      "Level 7",
	"d8 eye drop":                  "Level 8",
	"d8 armos chest":               "Level 8",
	"d8 SW lava chest":             "Level 8",
	"d8 three eyes chest":          "Level 8",
	"d8 hardhat drop":              "Level 8",
	"d8 spike room":                "Level 8",
	"d8 spinner chest":             "Level 8",
	"d8 magnet ball room":          "Level 8",
	"d8 darknut chest":             "Level 8",
	"d8 ghost armos drop":          "Level 8",
	"d8 pols voice chest":          "Level 8",
	"d8 SE lava chest":             "Level 8",
	"d8 spark chest":               "Level 8",
	"d8 boss":                      "Level 8",
	"horon village seed tree":      "Horon Village",
	"woods of winter seed tree":    "Woods of Winter",
	"north horon seed tree":        "North Horon",
	"spool swamp seed tree":        "Spool Swamp",
	"sunken city seed tree":        "Sunken City",
	"tarm ruins seed tree":         "Tarm Ruins",
}

var agesAreaMap = map[string]string{
	"starting chest":           "Forest of Time",
	"nayru's house":            "Forest of Time",
	"maku tree":                "Lynna City", // this one's kind of weird
	"grave under tree":         "Yoll Graveyard",
	"graveyard poe":            "Yoll Graveyard",
	"cheval's test":            "Yoll Graveyard",
	"cheval's invention":       "Yoll Graveyard",
	"south shore dirt":         "South Shore",
	"balloon guy's gift":       "Forest of Time",
	"balloon guy's upgrade":    "Forest of Time",
	"shop, 150 rupees":         "Lynna City",
	"defeat great moblin":      "Rolling Ridge",
	"goron elder":              "Rolling Ridge Base",
	"target carts 1":           "Rolling Ridge",
	"target carts 2":           "Rolling Ridge",
	"goron dance present":      "Rolling Ridge Base",
	"trade rock brisket":       "Rolling Ridge Base",
	"trade goron vase":         "Rolling Ridge Base",
	"big bang game":            "Rolling Ridge",
	"goron shooting gallery":   "Rolling Ridge",
	"trade lava juice":         "Rolling Ridge",
	"rescue nayru":             "Ambi's Palace",
	"king zora":                "Zora Village",
	"library present":          "Zora Seas",
	"zora's reward":            "Sea of Storms",
	"piratian captain":         "Sea of Storms",
	"lynna city chest":         "Lynna City",
	"fairies' woods chest":     "Fairies' Woods",
	"fairies' coast chest":     "Zora Village",
	"zora seas chest":          "Zora Seas",
	"talus peaks chest":        "Talus Peaks",
	"under moblin keep":        "Rolling Ridge",
	"nuun highlands cave":      "Nuun Highlands",
	"zora village present":     "Zora Village",
	"pool in d6 entrance":      "Rolling Ridge Base",
	"mayor plen's house":       "Lynna City",
	"under crescent island":    "Crescent Island",
	"goron's hiding place":     "Rolling Ridge",
	"ridge base chest":         "Rolling Ridge Base",
	"ridge NE cave present":    "Rolling Ridge",
	"goron diamond cave":       "Rolling Ridge",
	"ridge west cave":          "Rolling Ridge",
	"zora NW cave":             "Zora Village",
	"zora palace chest":        "Zora Village",
	"black tower worker":       "The Black Tower",
	"deku forest soldier":      "Deku Forest",
	"wild tokay game":          "Crescent Island",
	"hidden tokay cave":        "Crescent Island",
	"symmetry city brother":    "Symmetry City",
	"tokkey's composition":     "Talus Peaks",
	"goron dance, with letter": "Rolling Ridge Base",
	"library past":             "Zora Seas",
	"sea of no return":         "Sea of No Return",
	"bomb goron head":          "Rolling Ridge",
	"tokay bomb cave":          "Crescent Island",
	"fisher's island cave":     "Zora Seas",
	"ridge bush cave":          "Rolling Ridge",
	"sea of storms past":       "Sea of Storms",
	"deku forest cave west":    "Deku Forest",
	"ridge diamonds past":      "Rolling Ridge Base",
	"ridge base past":          "Rolling Ridge Base",
	"deku forest cave east":    "Deku Forest",
	"ambi's palace chest":      "Ambi's Palace",
	"tokay crystal cave":       "Crescent Island",
	"tokay pot cave":           "Crescent Island",
	"d1 button chest":          "Level 1",
	"d1 crystal room":          "Level 1",
	"d1 crossroads":            "Level 1",
	"d1 west terrace":          "Level 1",
	"d1 pot chest":             "Level 1",
	"d1 east terrace":          "Level 1",
	"d1 basement":              "Level 1",
	"d1 boss":                  "Level 1",
	"d2 color room":            "Level 2",
	"d2 bombed terrace":        "Level 2",
	"d2 moblin platform":       "Level 2",
	"d2 rope room":             "Level 2",
	"d2 thwomp shelf":          "Level 2",
	"d2 thwomp tunnel":         "Level 2",
	"d2 boss":                  "Level 2",
	"d3 bridge chest":          "Level 3",
	"d3 B1F east":              "Level 3",
	"d3 torch chest":           "Level 3",
	"d3 conveyor belt room":    "Level 3",
	"d3 mimic room":            "Level 3",
	"d3 bush beetle room":      "Level 3",
	"d3 crossroads":            "Level 3",
	"d3 pols voice chest":      "Level 3",
	"d3 boss":                  "Level 3",
	"d4 lava pot chest":        "Level 4",
	"d4 small floor puzzle":    "Level 4",
	"d4 first chest":           "Level 4",
	"d4 minecart chest":        "Level 4",
	"d4 boss":                  "Level 4",
	"d5 red peg chest":         "Level 5",
	"d5 owl puzzle":            "Level 5",
	"d5 six-statue puzzle":     "Level 5",
	"d5 diamond chest":         "Level 5",
	"d5 blue peg chest":        "Level 5",
	"d5 boss":                  "Level 5",
	"d6 present vire chest":    "Level 6",
	"d6 present RNG chest":     "Level 6",
	"d6 present diamond chest": "Level 6",
	"d6 present beamos chest":  "Level 6",
	"d6 present channel chest": "Level 6",
	"d6 past spear chest":      "Level 6",
	"d6 past color room":       "Level 6",
	"d6 past pool chest":       "Level 6",
	"d6 past wizzrobe chest":   "Level 6",
	"d6 boss":                  "Level 6",
	"d7 pot island chest":      "Level 7",
	"d7 stairway chest":        "Level 7",
	"d7 miniboss chest":        "Level 7",
	"d7 crab chest":            "Level 7",
	"d7 spike chest":           "Level 7",
	"d7 hallway chest":         "Level 7",
	"d7 post-hallway chest":    "Level 7",
	"d7 boss":                  "Level 7",
	"d8 B3F chest":             "Level 8",
	"d8 NW slate chest":        "Level 8",
	"d8 NE slate chest":        "Level 8",
	"d8 ghini chest":           "Level 8",
	"d8 SE slate chest":        "Level 8",
	"d8 SW slate chest":        "Level 8",
	"d8 sarcophagus chest":     "Level 8",
	"d8 blue peg chest":        "Level 8",
	"d8 floor puzzle":          "Level 8",
	"d8 tile room":             "Level 8",
	"d8 boss":                  "Level 8",
	"symmetry city tree":       "Symmetry City",
	"south lynna tree":         "South Lynna",
	"crescent island tree":     "Crescent Island",
	"zora village tree":        "Zora Village",
	"rolling ridge west tree":  "Rolling Ridge",
	"ambi's palace tree":       "Ambi's Palace",
	"rolling ridge east tree":  "Rolling Ridge",
	"deku forest tree":         "Deku Forest",
	"shop, 30 rupees":          "Lynna City",
}
