package logic

var ringNodes = map[string]*Node{
	"friendship ring": Root(),
	"power ring L-1":  Root(),
	"power ring L-2":  Root(),
	"power ring L-3":  Root(),
	"armor ring L-1":  Root(),
	"armor ring L-2":  Root(),
	"armor ring L-3":  Root(),
	"red ring":        Root(),
	"blue ring":       Root(),
	"green ring":      Root(),
	"cursed ring":     Root(),
	"expert's ring":   Root(),
	"blast ring":      Root(),
	"rang ring L-1":   Root(),
	"GBA time ring":   Root(),
	"maple's ring":    Root(),
	"steadfast ring":  Root(),
	"pegasus ring":    Root(),
	"toss ring":       Root(),
	"heart ring L-1":  Root(),
	"heart ring L-2":  Root(),
	"swimmer's ring":  Root(),
	"charge ring":     Root(),
	"light ring L-1":  Root(),
	"light ring L-2":  Root(),
	"bomber's ring":   Root(),
	"green luck ring": Root(),
	"blue luck ring":  Root(),
	"gold luck ring":  Root(),
	"red luck ring":   Root(),
	"green holy ring": Root(),
	"blue holy ring":  Root(),
	"red holy ring":   Root(),
	"snowshoe ring":   Root(),
	"roc's ring":      Root(),
	"quicksand ring":  Root(),
	"red joy ring":    Root(),
	"blue joy ring":   Root(),
	"gold joy ring":   Root(),
	"green joy ring":  Root(),
	"discovery ring":  Root(),
	"rang ring L-2":   Root(),
	"octo ring":       Root(),
	"moblin ring":     Root(),
	"like-like ring":  Root(),
	"subrosian ring":  Root(),
	"first gen ring":  Root(),
	"spin ring":       Root(),
	"bombproof ring":  Root(),
	"energy ring":     Root(),
	"dbl. edged ring": Root(),
	"GBA nature ring": Root(),
	"slayer's ring":   Root(),
	"rupee ring":      Root(),
	"victory ring":    Root(),
	"sign ring":       Root(),
	"100th ring":      Root(),
	"whisp ring":      Root(),
	"gasha ring":      Root(),
	"peace ring":      Root(),
	"zora ring":       Root(),
	"fist ring":       Root(),
	"whimsical ring":  Root(),
	"protection ring": Root(),
}
